'use client';

import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';

export type Language = 'en' | 'es' | 'ar' | 'ko' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Header
    'header.title': 'Seattle Auto Haus',
    'header.subtitle': 'Premium Vehicle Dealership',
    'nav.home': 'Home',
    'nav.inventory': 'Inventory',
    'nav.about': 'About',
    'settings.language': 'Language',
    'settings.darkMode': 'Dark Mode',
    'settings.lightMode': 'Light Mode',
    'settings.system': 'System',
    'settings.theme': 'Theme',
    'settings.help': 'Help',
    
    // Home page
    'hero.title': 'Find Your Perfect Car',
    'hero.subtitle': 'Discover our premium selection of luxury and performance vehicles with instant search and real-time results',
    'stats.vehicles': 'Vehicles in Stock',
    'stats.brands': 'Brands Available',
    'stats.satisfaction': 'Customer Satisfaction',
    'featured.title': 'Featured Vehicles',
    'featured.subtitle': 'Hand-picked vehicles from our premium collection',
    'featured.viewAll': 'View All Vehicles',
    'testimonials.title': 'What Our Customers Say',
    'testimonials.subtitle': 'Real experiences from satisfied customers',
    'footer.description': 'Premium vehicle dealership serving the greater Seattle area',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.contact': 'Contact Us',
    
    // Inventory page specific translations
    'Our Inventory': 'Our Inventory',
    'Browse our extensive selection of quality vehicles': 'Browse our extensive selection of quality vehicles',
    'Search cars...': 'Search cars...',
    'Make': 'Make',
    'All Makes': 'All Makes',
    'Body Style': 'Body Style',
    'All Body Styles': 'All Body Styles',
    'Price Range': 'Price Range',
    'All Prices': 'All Prices',
    'Under $20,000': 'Under $20,000',
    '$20,000 - $40,000': '$20,000 - $40,000',
    '$40,000 - $60,000': '$40,000 - $60,000',
    '$60,000 - $80,000': '$60,000 - $80,000',
    '$80,000+': '$80,000+',
    'Year': 'Year',
    'All Years': 'All Years',
    'Showing': 'Showing',
    'of': 'of',
    'vehicles': 'vehicles',
    'Clear Filters': 'Clear Filters',
    'No vehicles found': 'No vehicles found',
    'Try adjusting your search criteria or filters': 'Try adjusting your search criteria or filters',
    'Clear All Filters': 'Clear All Filters',
    'Can\'t find what you\'re looking for?': 'Can\'t find what you\'re looking for?',
    'Contact us and we\'ll help you find the perfect vehicle': 'Contact us and we\'ll help you find the perfect vehicle',
    'Contact Us': 'Contact Us',
    'Schedule Test Drive': 'Schedule Test Drive',
    'View Details': 'View Details',
    'Featured': 'Featured',
    'New Arrival': 'New Arrival',
    'Special Offer': 'Special Offer',
    'miles': 'miles',
    
    // Language names
    'language.english': 'English',
    'language.spanish': 'Spanish',
    'language.arabic': 'Arabic',
    'language.korean': 'Korean',
    'language.chinese': 'Chinese',
    
    // Car status badges
    'car.status.featured': 'Featured',
    'car.status.newArrival': 'New Arrival',
    'car.status.specialOffer': 'Special Offer',
    
    // Car details
    'car.miles': 'miles',
    'car.vin': 'VIN',
    'car.stock': 'Stock',
    'car.viewDetails': 'View Details',
    
    // Home page sections
    'home.hero.title': 'Find Your Perfect Car',
    'home.hero.subtitle': 'Discover quality vehicles with competitive pricing and exceptional service',
    'home.hero.browseInventory': 'Browse Inventory',
    'home.hero.learnMore': 'Learn More',
    'home.featured.title': 'Featured Vehicles',
    'home.featured.subtitle': 'Our most popular and highly-rated vehicles',
    'home.featured.vehicle': 'Featured Vehicle',
    'home.newArrivals.title': 'New Arrivals',
    'home.newArrivals.subtitle': 'Fresh inventory just added to our lot',
    'home.specialOffers.title': 'Special Offers',
    'home.specialOffers.subtitle': 'Limited-time deals and special pricing',
    'home.contact.title': 'Ready to Get Started?',
    'home.contact.subtitle': 'Contact us today to schedule a test drive or discuss financing options',
    'home.contact.callNow': 'Call Now',
    'home.contact.visitUs': 'Visit Us',
    'home.whyChoose.title': 'Why Choose Autohaus?',
    'home.whyChoose.subtitle': 'We\'re committed to providing exceptional service and quality vehicles',
    'home.whyChoose.quality.title': 'Quality Vehicles',
    'home.whyChoose.quality.description': 'Every vehicle in our inventory is carefully inspected and maintained to the highest standards.',
    'home.whyChoose.financing.title': 'Flexible Financing',
    'home.whyChoose.financing.description': 'We work with multiple lenders to find the best financing options for your budget.',
    'home.whyChoose.service.title': 'Expert Service',
    'home.whyChoose.service.description': 'Our certified technicians provide reliable service and maintenance for all makes and models.',
    
    // Navigation and UI
    'ui.scrollToSeeMore': '← Scroll to see more vehicles →',
    'ui.loading': 'Loading cars...',
    'ui.previousSlide': 'Previous slide',
    'ui.nextSlide': 'Next slide',
    'ui.goToSlide': 'Go to slide',

    // Car specs lookup
    'car.specsLookup.title': 'Car Specifications Lookup',
    'car.specsLookup.vinLabel': 'VIN Number',
    'car.specsLookup.vinPlaceholder': 'Enter 17-character VIN',
    'car.specsLookup.searching': 'Searching...',
    'car.specsLookup.lookup': 'Lookup',
    'car.specsLookup.description': 'Enter the 17-character Vehicle Identification Number to lookup detailed specifications',
    'car.specsLookup.invalidVin': 'Invalid VIN',
    'car.specsLookup.invalidVinDescription': 'Please enter a valid 17-character VIN',
    'car.specsLookup.specsFound': 'Specifications Found',
    'car.specsLookup.specsFoundFor': 'Found specifications for',
    'car.specsLookup.noSpecsFound': 'No specifications found for this VIN',
    'car.specsLookup.lookupFailed': 'Specifications Lookup Failed',
    'car.specsLookup.unknownError': 'Unknown error occurred',

    // Common
    'common.loading': 'Loading...',
    'common.search': 'Search',
    'common.searching': 'Searching...',
    'common.selected': 'Selected',
    'common.features': 'Features',
    'common.quickActions': 'Quick Actions',
    'common.filters': 'Filters',
    'common.sortBy': 'Sort By',
    'common.priceRange': 'Price Range',
    'common.yearRange': 'Year Range',
    'common.clearFilters': 'Clear Filters',
    'common.apply': 'Apply',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.view': 'View',
    'common.details': 'Details',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.more': 'More',
    'common.less': 'Less',
    'common.all': 'All',
    'common.none': 'None',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.ok': 'OK',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.warning': 'Warning',
    'common.info': 'Information',
    'common.services': 'Services',
    'common.support': 'Support',
    'common.hoverToShow': 'Hover near the left edge to show/hide',
    'common.quickAccess': 'Quick access to tools & services',
    
    // About page
    'about.hero.title': 'About Seattle Auto Haus',
    'about.hero.subtitle': 'Your trusted partner in finding the perfect vehicle. We\'ve been serving the greater Seattle area with premium vehicles and exceptional service for over two decades.',
    'about.stats.vehicles': 'Vehicles in Stock',
    'about.stats.customers': 'Happy Customers',
    'about.stats.experience': 'Years of Experience',
    'about.stats.rating': 'Customer Rating',
    'about.story.title': 'Our Story',
    'about.story.p1': 'Founded in 1999, Seattle Auto Haus began as a small family-owned dealership with a simple mission: to provide the highest quality vehicles with the most transparent and honest service in the industry.',
    'about.story.p2': 'Over the years, we\'ve grown to become one of the most trusted names in the Seattle automotive market, specializing in luxury and performance vehicles while maintaining our commitment to customer satisfaction.',
    'about.story.p3': 'Our team of certified technicians and sales professionals are passionate about cars and dedicated to helping you find the perfect vehicle that fits your lifestyle and budget.',
    'about.values.title': 'Our Values',
    'about.values.subtitle': 'The principles that guide everything we do',
    'about.values.trust.title': 'Trust & Transparency',
    'about.values.trust.description': 'We believe in complete transparency in all our dealings, from pricing to vehicle history.',
    'about.values.quality.title': 'Quality & Excellence',
    'about.values.quality.description': 'Every vehicle in our inventory meets our strict quality standards and thorough inspection process.',
    'about.values.customer.title': 'Customer First',
    'about.values.customer.description': 'Your satisfaction is our priority. We\'re here to help you find the perfect vehicle.',
    'about.contact.title': 'Get In Touch',
    'about.contact.subtitle': 'Have questions? We\'d love to hear from you.',
    'about.contact.form.title': 'Send us a message',
    'about.contact.form.description': 'Fill out the form below and we\'ll get back to you as soon as possible.',
    'about.contact.form.name': 'Name',
    'about.contact.form.email': 'Email',
    'about.contact.form.phone': 'Phone',
    'about.contact.form.message': 'Message',
    'about.contact.form.submit': 'Send Message',
    'about.contact.info.title': 'Contact Information',
    'about.contact.info.address': 'Address',
    'about.contact.info.address.value': '1234 Auto Drive<br />Seattle, WA 98101',
    'about.contact.info.phone': 'Phone',
    'about.contact.info.phone.value': '(206) 555-0123<br />(206) 555-0124',
    'about.contact.info.email': 'Email',
    'about.contact.info.email.value': 'info@seattleautohaus.com<br />sales@seattleautohaus.com',
    'about.contact.info.hours': 'Business Hours',
    'about.contact.info.hours.value': 'Monday - Friday: 9:00 AM - 8:00 PM<br />Saturday: 9:00 AM - 6:00 PM<br />Sunday: 11:00 AM - 5:00 PM',
    'about.contact.social.title': 'Follow Us',
    'about.contact.social.facebook': 'Facebook',
    'about.contact.social.twitter': 'Twitter',
    'about.contact.social.instagram': 'Instagram',
    'about.contact.social.linkedin': 'LinkedIn',
    'about.location.title': 'Find Us',
    'about.location.subtitle': 'Visit our dealership in the heart of Seattle',
    'about.location.description': 'Located in the vibrant downtown Seattle area, easily accessible from major highways',
    'about.location.button': 'Open in Google Maps',
    'about.testimonials.title': 'What Our Customers Say',
    'about.testimonials.subtitle': 'Don\'t just take our word for it',
    'about.testimonials.testimonial1.content': 'Seattle Auto Haus made buying my dream car an amazing experience. Their team was professional, honest, and truly cared about finding the right vehicle for me.',
    'about.testimonials.testimonial1.author': 'Sarah Johnson',
    'about.testimonials.testimonial1.role': 'BMW 3 Series Owner',
    'about.testimonials.testimonial2.content': 'The quality of vehicles and level of service exceeded my expectations. I\'ve been a customer for years and they never disappoint.',
    'about.testimonials.testimonial2.author': 'Michael Chen',
    'about.testimonials.testimonial2.role': 'Mercedes C-Class Owner',
    'about.testimonials.testimonial3.content': 'From the first phone call to driving off the lot, everything was perfect. Their attention to detail and customer service is unmatched.',
    'about.testimonials.testimonial3.author': 'David Rodriguez',
    'about.testimonials.testimonial3.role': 'Audi A4 Owner',
    
    // Car detail page
    'car.back': 'Back to Inventory',
    'car.contact.title': 'Contact Us About This Vehicle',
    'car.contact.description': 'Interested in this vehicle? Send us a message and we\'ll get back to you as soon as possible.',
    'car.contact.name': 'Name',
    'car.contact.email': 'Email',
    'car.contact.phone': 'Phone',
    'car.contact.message': 'Message',
    'car.contact.submit': 'Send Message',
    'car.contact.success': 'Thank you for your message! We will get back to you soon.',
    'car.specs.title': 'Vehicle Specifications',
    'car.specs.vin': 'VIN',
    'car.specs.stock': 'Stock Number',
    'car.specs.exterior': 'Exterior Color',
    'car.specs.interior': 'Interior Color',
    'car.specs.transmission': 'Transmission',
    'car.specs.fuel': 'Fuel Type',
    'car.specs.engine': 'Engine',
    'car.specs.body': 'Body Style',
    'car.specs.doors': 'Doors',
    'car.specs.passengers': 'Passengers',
    'car.features.title': 'Features',
    'car.features.standard': 'Standard Features',
    'car.description': 'Vehicle Description',
    'car.loading': 'Loading car details...',
    'car.notFound': 'Car not found',
    'car.notFound.description': 'The car you\'re looking for doesn\'t exist.',
    'car.vehicleInformation': 'Vehicle Information',
    'car.year': 'Year',
    'car.make': 'Make',
    'car.model': 'Model',
    'car.bodyStyle': 'Body Style',
    'car.transmission': 'Transmission',
    'car.fuelType': 'Fuel Type',
    'car.exteriorColor': 'Exterior Color',
    'car.interiorColor': 'Interior Color',
    'car.mileage': 'miles',
    'car.interested': 'Interested in this vehicle?',
    'car.contactDealer': 'Contact Dealer',
    'car.scheduleTestDrive': 'Schedule Test Drive',
    'car.getFinancing': 'Get Financing',
    'car.performance': 'Performance',
    'car.efficiency': 'Efficiency',
    'car.dimensions': 'Dimensions',
    'car.features': 'Features',
    'car.performanceSpecs': 'Performance Specifications',
    'car.horsepower': 'Horsepower',
    'car.torque': 'Torque',
    'car.acceleration': '0-60 mph',
    'car.topSpeed': 'Top Speed',
    'car.fuelEfficiency': 'Fuel Efficiency',
    'car.cityMpg': 'City MPG',
    'car.highwayMpg': 'Highway MPG',
    'car.combinedMpg': 'Combined MPG',
    'car.fuelCapacity': 'Fuel Tank Capacity',
    'car.physicalDimensions': 'Physical Dimensions',
    'car.length': 'Length',
    'car.width': 'Width',
    'car.height': 'Height',
    'car.wheelbase': 'Wheelbase',
    'car.weight': 'Weight',
    'car.groundClearance': 'Ground Clearance',
    'car.featuresCapacity': 'Features & Capacity',
    'car.cargoVolume': 'Cargo Volume',
    'car.towingCapacity': 'Towing Capacity',
    'car.additionalFeatures': 'Additional Features',
    'car.atRpm': '@ RPM',
    'car.lbFt': 'lb-ft',
    'car.seconds': 'seconds',
    'car.mph': 'mph',
    'car.urbanDriving': 'urban driving',
    'car.highwayDriving': 'highway driving',
    'car.overallAverage': 'overall average',
    'car.gallons': 'gallons',
    'car.inches': 'inches',
    'car.lbs': 'lbs',
    'car.cubicFeet': 'cubic feet',
    'car.stockNumber': 'Stock #',
    'car.vin': 'VIN',
    'car.doors': 'Doors',
    'car.passengers': 'Passengers',
    'car.featured': 'Featured',
    'car.newArrival': 'New Arrival',
    'car.specialOffer': 'Special Offer',
    
    // Inventory page
    'inventory.title': 'Vehicle Inventory',
    'inventory.subtitle': 'Browse our complete selection of quality vehicles',
    'inventory.searchPrompt': 'Search by make, model, year, price, or features...',
    'inventory.searchPromptSubtitle': 'Use the search bar above to find vehicles in our inventory',
    'inventory.searchResults': 'Search results for',
    'inventory.clearSearch': 'Clear Search',
    'inventory.showing': 'Showing',
    'inventory.of': 'of',
    'inventory.vehicles': 'vehicles',
    'inventory.searching': 'Searching inventory...',
    'inventory.noResults': 'No vehicles found',
    'inventory.tryAdjusting': 'Try adjusting your search criteria or filters',
    'inventory.viewDetails': 'View Details',
    'inventory.previous': 'Previous',
    'inventory.page': 'Page',
    'inventory.next': 'Next',
    'inventory.featured': 'Featured Vehicles',
    'inventory.newArrivals': 'New Arrivals',
    'inventory.specialOffers': 'Special Offers',
    'inventory.recentlyViewed': 'Recently Viewed',
    'inventory.priceRange': 'Price Range',
    'inventory.yearRange': 'Year Range',
    'inventory.bodyStyle': 'Body Style',
    'inventory.fuelType': 'Fuel Type',
    'inventory.financing': 'Financing',
    'inventory.tradeIn': 'Trade-In',
    'inventory.warranty': 'Warranty',
    'inventory.maintenance': 'Maintenance',
    'inventory.liveChat': 'Live Chat',
    'inventory.phoneSupport': 'Phone Support',
    'inventory.emailSupport': 'Email Support',
    'inventory.faq': 'FAQ',
    
    // Additional inventory keys needed by the page
    'inventory.ourInventory': 'Our Inventory',
    'inventory.browseExtensive': 'Browse our extensive selection of quality vehicles',
    'inventory.searchCars': 'Search cars...',
    'inventory.make': 'Make',
    'inventory.allMakes': 'All Makes',
    'inventory.allBodyStyles': 'All Body Styles',
    'inventory.allPrices': 'All Prices',
    'inventory.under20000': 'Under $20,000',
    'inventory.price20000to40000': '$20,000 - $40,000',
    'inventory.price40000to60000': '$40,000 - $60,000',
    'inventory.price60000to80000': '$60,000 - $80,000',
    'inventory.price80000plus': '$80,000+',
    'inventory.year': 'Year',
    'inventory.allYears': 'All Years',
    'inventory.clearFilters': 'Clear Filters',
    'inventory.noVehiclesFound': 'No vehicles found',
    'inventory.tryAdjustingCriteria': 'Try adjusting your search criteria or filters',
    'inventory.clearAllFilters': 'Clear All Filters',
    'inventory.cantFind': 'Can\'t find what you\'re looking for?',
    'inventory.contactUsHelp': 'Contact us and we\'ll help you find the perfect vehicle',
    'inventory.contactUs': 'Contact Us',
    'inventory.scheduleTestDrive': 'Schedule Test Drive',
    'inventory.loading': 'Loading inventory...',
    
    // Search section (home page & inventory)
    'search.title': 'Search Vehicles',
    'search.subtitle': 'Find your perfect vehicle',
    'search.placeholder': 'Search by make, model, year, price, or features...',
    'search.button': 'Search',
    'search.quickResults': 'Quick Results',
    'search.recent': 'Recent Searches',
    'search.popular': 'Popular Searches',
    
    // Admin dashboard
    'admin.dashboard.title': 'Admin Dashboard',
    'admin.dashboard.refreshData': 'Refresh Data',
    'admin.dashboard.refreshing': 'Refreshing...',
    'admin.dashboard.autoRefreshOn': 'Auto-Refresh On',
    'admin.dashboard.autoRefreshOff': 'Auto-Refresh Off',
    'admin.dashboard.lastUpdated': 'Last updated',
    'admin.dashboard.overview': 'Overview',
    'admin.dashboard.addCar': 'Add Car',
    'admin.dashboard.manageCars': 'Manage Cars',
    'admin.dashboard.statistics': 'Statistics',
    'admin.dashboard.settings': 'Settings',
    'admin.dashboard.totalAvailable': 'Total Available',
    'admin.dashboard.carsInInventory': 'Cars in inventory',
    'admin.dashboard.featuredVehicles': 'Featured Vehicles',
    'admin.dashboard.currentlyFeatured': 'Currently featured',
    'admin.dashboard.newArrivals': 'New Arrivals',
    'admin.dashboard.recentlyAdded': 'Recently added',
    'admin.dashboard.specialOffers': 'Special Offers',
    'admin.dashboard.activeOffers': 'Active offers',
    'admin.dashboard.recentlyActive': 'Recently Active',
    'admin.dashboard.last7Days': 'Last 7 days',
    'admin.dashboard.nhtsaSpecsLookup': 'NHTSA Specs Lookup',
    'admin.dashboard.autoFetchSpecs': 'Auto-fetch car specifications from NHTSA database',
    'admin.dashboard.autoFetchSpecsButton': 'Auto Fetch Specs from NHTSA',
    'admin.dashboard.carSpecificationsLookup': 'Car Specifications Lookup',
    'admin.dashboard.fetchDetailedSpecs': 'Fetch detailed car specifications from the NHTSA vPIC database',
    'admin.dashboard.quickActions': 'Quick Actions',
    'admin.dashboard.quickActionsDescription': 'Use the tabs above to manage your inventory, add new cars, and view detailed statistics.',
    'admin.dashboard.addNewCar': 'Add New Car',
    'admin.dashboard.viewAllCars': 'View All Cars',
    'admin.dashboard.realTimeStats': 'Real-Time Car Statistics',
    'admin.dashboard.autoCalculated': 'These statistics are automatically calculated from your current car inventory and update in real-time.',
    'admin.dashboard.inventoryStatus': 'Inventory Status',
    'admin.dashboard.activityStatus': 'Activity Status',
    'admin.dashboard.dataAutoRefresh': 'Data automatically refreshes when you navigate between tabs or use the refresh button.',
    'admin.dashboard.refreshNow': 'Refresh Now',
    'admin.dashboard.themeLanguageSettings': 'Theme & Language Settings',
    'admin.dashboard.autoDetectDescription': 'Your website automatically detects your device\'s theme and language preferences. You can also manually override these settings.',
    
    // Car form
    'carForm.title': 'Add New Vehicle',
    'carForm.vin': 'VIN Number',
    'carForm.vinPlaceholder': 'Enter 17-character VIN',
    'carForm.price': 'Price',
    'carForm.pricePlaceholder': 'Enter price in USD',
    'carForm.mileage': 'Mileage',
    'carForm.mileagePlaceholder': 'Enter mileage',
    'carForm.stockNumber': 'Stock Number',
    'carForm.stockNumberPlaceholder': 'Enter stock number',
    'carForm.description': 'Description',
    'carForm.descriptionPlaceholder': 'Enter vehicle description',
    'carForm.exteriorColor': 'Exterior Color',
    'carForm.exteriorColorPlaceholder': 'Enter exterior color',
    'carForm.interiorColor': 'Interior Color',
    'carForm.interiorColorPlaceholder': 'Enter interior color',
    'carForm.doors': 'Number of Doors',
    'carForm.doorsPlaceholder': 'Enter number of doors',
    'carForm.passengers': 'Number of Passengers',
    'carForm.passengersPlaceholder': 'Enter number of passengers',
    'carForm.features': 'Features',
    'carForm.featuresPlaceholder': 'Enter vehicle features',
    'carForm.transmission': 'Transmission',
    'carForm.transmissionPlaceholder': 'Enter transmission type',
    'carForm.engine': 'Engine',
    'carForm.enginePlaceholder': 'Enter engine details',
    'carForm.fuelType': 'Fuel Type',
    'carForm.fuelTypePlaceholder': 'Enter fuel type',
    'carForm.driveType': 'Drive Type',
    'carForm.driveTypePlaceholder': 'Enter drive type',
    'carForm.images': 'Vehicle Images',
    'carForm.uploadImages': 'Upload Images',
    'carForm.selectFiles': 'Select Files',
    'carForm.primaryImage': 'Primary Image',
    'carForm.removeImage': 'Remove Image',
    'carForm.fetchSpecs': 'Fetch Specifications',
    'carForm.specsFetched': 'Specifications fetched successfully!',
    'carForm.addVehicle': 'Add Vehicle',
    'carForm.vehicleAdded': 'Vehicle added successfully!',
    'carForm.errorAdding': 'Error adding vehicle',
    'carForm.invalidVin': 'Invalid VIN',
    'carForm.vinRequired': 'VIN is required and must be 17 characters',
    'carForm.priceRequired': 'Price is required',
    'carForm.mileageRequired': 'Mileage is required',
    'carForm.stockNumberRequired': 'Stock number is required',
    
    // Car grid
    'carGrid.title': 'Manage Vehicles',
    'carGrid.search': 'Search vehicles...',
    'carGrid.statusFilter': 'Status Filter',
    'carGrid.allStatuses': 'All Statuses',
    'carGrid.featured': 'Featured',
    'carGrid.newArrival': 'New Arrival',
    'carGrid.specialOffer': 'Special Offer',
    'carGrid.edit': 'Edit',
    'carGrid.save': 'Save',
    'carGrid.cancel': 'Cancel',
    'carGrid.delete': 'Delete',
    'carGrid.confirmDelete': 'Are you sure you want to delete this vehicle?',
    'carGrid.vehicleDeleted': 'Vehicle deleted successfully',
    'carGrid.vehicleUpdated': 'Vehicle updated successfully',
    'carGrid.errorUpdating': 'Error updating vehicle',
    'carGrid.errorDeleting': 'Error deleting vehicle',
    'carGrid.fetchSpecs': 'Fetch Specs',
    'carGrid.specsFetched': 'Specifications fetched successfully!',
    'carGrid.noCars': 'No vehicles found',
    'carGrid.loading': 'Loading vehicles...',
    
    // Toast messages
    'toast.success': 'Success',
    'toast.error': 'Error',
    'toast.warning': 'Warning',
    'toast.info': 'Information',
    'toast.vehicleAdded': 'Vehicle added successfully!',
    'toast.vehicleUpdated': 'Vehicle updated successfully!',
    'toast.vehicleDeleted': 'Vehicle deleted successfully!',
    'toast.specsFetched': 'Specifications fetched successfully!',
    'toast.errorFetchingSpecs': 'Error fetching specifications',
    'toast.invalidVin': 'Invalid VIN format',
    'toast.vinRequired': 'VIN is required',
    'toast.priceRequired': 'Price is required',
    'toast.mileageRequired': 'Mileage is required',
    'toast.stockNumberRequired': 'Stock number is required',
    
    // Form validation
    'validation.required': 'This field is required',
    'validation.invalidFormat': 'Invalid format',
    'validation.minLength': 'Minimum length is {min} characters',
    'validation.maxLength': 'Maximum length is {max} characters',
    'validation.invalidVin': 'VIN must be exactly 17 characters',
    'validation.invalidPrice': 'Price must be a positive number',
    'validation.invalidMileage': 'Mileage must be a positive number',
    
    // Loading states
    'loading.general': 'Loading...',
    'loading.cars': 'Loading cars...',
    'loading.inventory': 'Loading inventory...',
    'loading.carDetails': 'Loading car details...',
    'loading.specs': 'Loading specifications...',
    'loading.images': 'Loading images...',
    'loading.search': 'Searching...',
    'loading.submitting': 'Submitting...',
    'loading.saving': 'Saving...',
    'loading.deleting': 'Deleting...',
    
    // Error messages
    'error.general': 'An error occurred',
    'error.network': 'Network error. Please check your connection.',
    'error.notFound': 'Not found',
    'error.unauthorized': 'Unauthorized access',
    'error.forbidden': 'Access forbidden',
    'error.serverError': 'Server error. Please try again later.',
    'error.invalidInput': 'Invalid input provided',
    'error.validationFailed': 'Validation failed',
    'error.carNotFound': 'Car not found',
    'error.failedToLoad': 'Failed to load data',
    'error.failedToSave': 'Failed to save data',
    'error.failedToDelete': 'Failed to delete data',
    
    // Success messages
    'success.general': 'Operation completed successfully',
    'success.carAdded': 'Car added successfully',
    'success.carUpdated': 'Car updated successfully',
    'success.carDeleted': 'Car deleted successfully',
    'success.specsFetched': 'Specifications fetched successfully',
    'success.imageUploaded': 'Image uploaded successfully',
    'success.formSubmitted': 'Form submitted successfully',
    
    // Confirmation dialogs
    'confirm.delete': 'Are you sure you want to delete this item?',
    'confirm.deleteCar': 'Are you sure you want to delete this vehicle?',
    'confirm.cancelEdit': 'Are you sure you want to cancel editing? All changes will be lost.',
    'confirm.unsavedChanges': 'You have unsaved changes. Are you sure you want to leave?',
    
    // Pagination
    'pagination.previous': 'Previous',
    'pagination.next': 'Next',
    'pagination.page': 'Page',
    'pagination.of': 'of',
    'pagination.showing': 'Showing',
    'pagination.entries': 'entries',
    'pagination.perPage': 'per page',
    
    // Filters
    'filters.title': 'Filters',
    'filters.clearAll': 'Clear All Filters',
    'filters.apply': 'Apply Filters',
    'filters.reset': 'Reset Filters',
    'filters.priceRange': 'Price Range',
    'filters.yearRange': 'Year Range',
    'filters.bodyStyle': 'Body Style',
    'filters.fuelType': 'Fuel Type',
    'filters.transmission': 'Transmission',
    'filters.make': 'Make',
    'filters.model': 'Model',
    'filters.mileage': 'Mileage',
    'filters.features': 'Features',
    'filters.status': 'Status',
    
    // Sort options
    'sort.title': 'Sort By',
    'sort.priceLowToHigh': 'Price: Low to High',
    'sort.priceHighToLow': 'Price: High to Low',
    'sort.yearNewToOld': 'Year: New to Old',
    'sort.yearOldToNew': 'Year: Old to New',
    'sort.mileageLowToHigh': 'Mileage: Low to High',
    'sort.mileageHighToLow': 'Mileage: High to Low',
    'sort.makeAZ': 'Make: A to Z',
    'sort.makeZA': 'Make: Z to A',
    'sort.modelAZ': 'Model: A to Z',
    'sort.modelZA': 'Model: Z to A',
    'sort.dateAdded': 'Date Added',
    'sort.featured': 'Featured First',
    'sort.newArrivals': 'New Arrivals First',
    'sort.specialOffers': 'Special Offers First',
    
    // Status indicators
    'status.available': 'Available',
    'status.sold': 'Sold',
    'status.reserved': 'Reserved',
    'status.inTransit': 'In Transit',
    'status.maintenance': 'In Maintenance',
    'status.featured': 'Featured',
    'status.newArrival': 'New Arrival',
    'status.specialOffer': 'Special Offer',
    'status.recentlyViewed': 'Recently Viewed',
    
    // Contact and actions
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Get in touch with our team',
    'contact.name': 'Name',
    'contact.email': 'Email',
    'contact.phone': 'Phone',
    'contact.message': 'Message',
    'contact.submit': 'Send Message',
    'contact.success': 'Message sent successfully!',
    'contact.error': 'Failed to send message',
    'contact.required': 'This field is required',
    'contact.invalidEmail': 'Please enter a valid email address',
    'contact.invalidPhone': 'Please enter a valid phone number',
    
    // Test drive
    'testDrive.title': 'Schedule Test Drive',
    'testDrive.subtitle': 'Book a test drive for this vehicle',
    'testDrive.date': 'Preferred Date',
    'testDrive.time': 'Preferred Time',
    'testDrive.notes': 'Additional Notes',
    'testDrive.schedule': 'Schedule Test Drive',
    'testDrive.scheduled': 'Test drive scheduled successfully!',
    'testDrive.error': 'Failed to schedule test drive',
    
    // Financing
    'financing.title': 'Get Financing',
    'financing.subtitle': 'Apply for financing on this vehicle',
    'financing.amount': 'Loan Amount',
    'financing.term': 'Loan Term',
    'financing.creditScore': 'Credit Score Range',
    'financing.apply': 'Apply for Financing',
    'financing.applied': 'Financing application submitted!',
    'financing.error': 'Failed to submit financing application',
    
    // Trade-in
    'tradeIn.title': 'Trade-In Your Vehicle',
    'tradeIn.subtitle': 'Get an estimate for your current vehicle',
    'tradeIn.make': 'Vehicle Make',
    'tradeIn.model': 'Vehicle Model',
    'tradeIn.year': 'Vehicle Year',
    'tradeIn.mileage': 'Current Mileage',
    'tradeIn.condition': 'Vehicle Condition',
    'tradeIn.estimate': 'Get Estimate',
    'tradeIn.estimated': 'Trade-in estimate received!',
    'tradeIn.error': 'Failed to get trade-in estimate',
    
    // Warranty
    'warranty.title': 'Warranty Information',
    'warranty.subtitle': 'Learn about our warranty coverage',
    'warranty.basic': 'Basic Warranty',
    'warranty.powertrain': 'Powertrain Warranty',
    'warranty.corrosion': 'Corrosion Warranty',
    'warranty.emissions': 'Emissions Warranty',
    'warranty.additional': 'Additional Coverage',
    
    // Maintenance
    'maintenance.title': 'Maintenance Services',
    'maintenance.subtitle': 'Keep your vehicle in top condition',
    'maintenance.oilChange': 'Oil Change',
    'maintenance.tireRotation': 'Tire Rotation',
    'maintenance.brakeService': 'Brake Service',
    'maintenance.tuneUp': 'Tune-Up',
    'maintenance.inspection': 'Vehicle Inspection',
    'maintenance.schedule': 'Schedule Service',
    
    // FAQ
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Find answers to common questions',
    'faq.general': 'General Questions',
    'faq.financing': 'Financing Questions',
    'faq.warranty': 'Warranty Questions',
    'faq.service': 'Service Questions',
    'faq.inventory': 'Inventory Questions',
    
    // Social media
    'social.facebook': 'Follow us on Facebook',
    'social.twitter': 'Follow us on Twitter',
    'social.instagram': 'Follow us on Instagram',
    'social.linkedin': 'Follow us on LinkedIn',
    'social.youtube': 'Subscribe to our YouTube channel',
    
    // Legal
    'legal.privacy': 'Privacy Policy',
    'legal.terms': 'Terms of Service',
    'legal.cookies': 'Cookie Policy',
    'legal.accessibility': 'Accessibility Statement',
    'legal.sitemap': 'Sitemap',
    
    // Accessibility
    'accessibility.menu': 'Main navigation menu',
    'accessibility.search': 'Search vehicles',
    'accessibility.language': 'Language selection',
    'accessibility.theme': 'Theme selection',
    'accessibility.skipToContent': 'Skip to main content',
    'accessibility.backToTop': 'Back to top',
    
    // SEO and meta
    'meta.home.title': 'Seattle Auto Haus - Premium Vehicle Dealership',
    'meta.home.description': 'Find your perfect car at Seattle Auto Haus. Browse our premium selection of luxury and performance vehicles with competitive pricing and exceptional service.',
    'meta.inventory.title': 'Vehicle Inventory - Seattle Auto Haus',
    'meta.inventory.description': 'Browse our complete selection of quality vehicles. Search by make, model, year, price, or features to find your perfect car.',
    'meta.about.title': 'About Seattle Auto Haus - Premium Vehicle Dealership',
    'meta.about.description': 'Learn about Seattle Auto Haus, your trusted partner in finding the perfect vehicle. Serving the greater Seattle area for over two decades.',
    'meta.admin.title': 'Admin Dashboard - Seattle Auto Haus',
    'meta.admin.description': 'Admin dashboard for managing vehicle inventory, adding new cars, and viewing detailed statistics.',
  },
  es: {
    'header.title': 'Seattle Auto Haus',
    'header.subtitle': 'Concesionario de Vehículos Premium',
    'nav.home': 'Inicio',
    'nav.inventory': 'Inventario',
    'nav.about': 'Acerca de',
    'settings.language': 'Idioma',
    'settings.darkMode': 'Modo Oscuro',
    'settings.lightMode': 'Modo Claro',
    'settings.system': 'Sistema',
    'settings.theme': 'Tema',
    'settings.help': 'Ayuda',
    'hero.title': 'Encuentra Tu Auto Perfecto',
    'hero.subtitle': 'Descubre nuestra selección premium de vehículos de lujo y rendimiento con búsqueda instantánea y resultados en tiempo real',
    'stats.vehicles': 'Vehículos en Stock',
    'stats.brands': 'Marcas Disponibles',
    'stats.satisfaction': 'Satisfacción del Cliente',
    'featured.title': 'Vehículos Destacados',
    'featured.subtitle': 'Vehículos seleccionados de nuestra colección premium',
    'featured.viewAll': 'Ver Todos los Vehículos',
    'testimonials.title': 'Lo Que Dicen Nuestros Clientes',
    'testimonials.subtitle': 'Experiencias reales de clientes satisfechos',
    'footer.description': 'Concesionario de vehículos premium sirviendo al área metropolitana de Seattle',
    'footer.privacy': 'Política de Privacidad',
    'footer.terms': 'Términos de Servicio',
    'footer.contact': 'Contáctenos',
    'inventory.title': 'Inventario de Vehículos',
    'inventory.subtitle': 'Explora nuestra selección completa de vehículos',
    'inventory.searchResults': 'Resultados de búsqueda para',
    'inventory.filters': 'Filtros',
    'inventory.sortBy': 'Ordenar Por',
    'inventory.priceRange': 'Rango de Precio',
    'inventory.yearRange': 'Rango de Año',
    'inventory.clearFilters': 'Limpiar Filtros',
    'inventory.searching': 'Buscando inventario...',
    'inventory.noResults': 'No se encontraron vehículos',
    'inventory.tryAdjusting': 'Intenta ajustar tus términos de búsqueda o filtros',
    'inventory.clearSearch': 'Limpiar Búsqueda',
    'inventory.searchPrompt': 'Buscar vehículos',
    'inventory.searchPromptSubtitle': 'Usa la barra de búsqueda arriba para encontrar vehículos en nuestro inventario',
    'inventory.showing': 'Mostrando',
    'inventory.of': 'de',
    'inventory.vehicles': 'vehículos',
    'inventory.for': 'para',
    'inventory.viewDetails': 'Ver Detalles',
    'inventory.previous': 'Anterior',
    'inventory.next': 'Siguiente',
    'inventory.page': 'Página',
    'inventory.featured': 'Vehículos Destacados',
    'inventory.newArrivals': 'Nuevas Llegadas',
    'inventory.specialOffers': 'Ofertas Especiales',
    'inventory.recentlyViewed': 'Vistos Recientemente',
    // Additional inventory keys needed by the page
    'inventory.ourInventory': 'Nuestro Inventario',
    'inventory.browseExtensive': 'Explora nuestra extensa selección de vehículos de calidad',
    'inventory.searchCars': 'Buscar autos...',
    'inventory.make': 'Marca',
    'inventory.allMakes': 'Todas las Marcas',
    'inventory.allBodyStyles': 'Todos los Estilos de Carrocería',
    'inventory.allPrices': 'Todos los Precios',
    'inventory.under20000': 'Menos de $20,000',
    'inventory.price20000to40000': '$20,000 - $40,000',
    'inventory.price40000to60000': '$40,000 - $60,000',
    'inventory.price60000to80000': '$60,000 - $80,000',
    'inventory.price80000plus': '$80,000+',
    'inventory.year': 'Año',
    'inventory.allYears': 'Todos los Años',
    'inventory.noVehiclesFound': 'No se encontraron vehículos',
    'inventory.tryAdjustingCriteria': 'Intenta ajustar tus criterios de búsqueda o filtros',
    'inventory.clearAllFilters': 'Limpiar Todos los Filtros',
    'inventory.cantFind': '¿No puedes encontrar lo que buscas?',
    'inventory.contactUsHelp': 'Contáctanos y te ayudaremos a encontrar el vehículo perfecto',
    'inventory.contactUs': 'Contáctanos',
    'inventory.scheduleTestDrive': 'Programar Prueba de Manejo',
    'inventory.loading': 'Cargando inventario...',
    // Search section (home page & inventory)
    'search.title': 'Buscar Vehículos',
    'search.subtitle': 'Encuentra tu vehículo perfecto',
    'search.placeholder': 'Buscar por marca, modelo, año, precio o características...',
    'search.button': 'Buscar',
    'search.quickResults': 'Resultados Rápidos',
    'search.recent': 'Búsquedas Recientes',
    'search.popular': 'Búsquedas Populares',
    // About page
    'about.hero.title': 'Acerca de Seattle Auto Haus',
    'about.hero.subtitle': 'Su socio de confianza para encontrar el vehículo perfecto. Hemos estado sirviendo al área metropolitana de Seattle con vehículos premium y servicio excepcional durante más de dos décadas.',
    'about.stats.vehicles': 'Vehículos en Stock',
    'about.stats.customers': 'Clientes Satisfechos',
    'about.stats.experience': 'Años de Experiencia',
    'about.stats.rating': 'Calificación del Cliente',
    'about.story.title': 'Nuestra Historia',
    'about.story.p1': 'Fundado en 1999, Seattle Auto Haus comenzó como un pequeño concesionario familiar con una misión simple: proporcionar vehículos de la más alta calidad con el servicio más transparente y honesto en la industria.',
    'about.story.p2': 'A lo largo de los años, hemos crecido para convertirnos en uno de los nombres más confiables en el mercado automotriz de Seattle, especializándonos en vehículos de lujo y rendimiento mientras mantenemos nuestro compromiso con la satisfacción del cliente.',
    'about.story.p3': 'Nuestro equipo de técnicos certificados y profesionales de ventas son apasionados por los autos y dedicados a ayudarle a encontrar el vehículo perfecto que se adapte a su estilo de vida y presupuesto.',
    'about.values.title': 'Nuestros Valores',
    'about.values.subtitle': 'Los principios que guían todo lo que hacemos',
    'about.values.trust.title': 'Confianza y Transparencia',
    'about.values.trust.description': 'Creemos en la transparencia completa en todos nuestros tratos, desde precios hasta historial del vehículo.',
    'about.values.quality.title': 'Calidad y Excelencia',
    'about.values.quality.description': 'Cada vehículo en nuestro inventario cumple con nuestros estrictos estándares de calidad y proceso de inspección exhaustivo.',
    'about.values.customer.title': 'Cliente Primero',
    'about.values.customer.description': 'Su satisfacción es nuestra prioridad. Estamos aquí para ayudarle a encontrar el vehículo perfecto.',
    'about.contact.title': 'Póngase en Contacto',
    'about.contact.subtitle': '¿Tiene preguntas? Nos encantaría saber de usted.',
    'about.contact.form.title': 'Envíenos un mensaje',
    'about.contact.form.description': 'Complete el formulario a continuación y nos pondremos en contacto con usted lo antes posible.',
    'about.contact.form.name': 'Nombre',
    'about.contact.form.email': 'Correo Electrónico',
    'about.contact.form.phone': 'Teléfono',
    'about.contact.form.message': 'Mensaje',
    'about.contact.form.submit': 'Enviar Mensaje',
    'about.contact.info.title': 'Información de Contacto',
    'about.contact.info.address': 'Dirección',
    'about.contact.info.address.value': '1234 Auto Drive<br />Seattle, WA 98101',
    'about.contact.info.phone': 'Teléfono',
    'about.contact.info.phone.value': '(206) 555-0123<br />(206) 555-0124',
    'about.contact.info.email': 'Correo Electrónico',
    'about.contact.info.email.value': 'info@seattleautohaus.com<br />sales@seattleautohaus.com',
    'about.contact.info.hours': 'Horario Comercial',
    'about.contact.info.hours.value': 'Lunes - Viernes: 9:00 AM - 8:00 PM<br />Sábado: 9:00 AM - 6:00 PM<br />Domingo: 11:00 AM - 5:00 PM',
    'about.contact.social.title': 'Síguenos',
    'about.contact.social.facebook': 'Facebook',
    'about.contact.social.twitter': 'Twitter',
    'about.contact.social.instagram': 'Instagram',
    'about.contact.social.linkedin': 'LinkedIn',
    'about.location.title': 'Encuéntranos',
    'about.location.subtitle': 'Visite nuestro concesionario en el corazón de Seattle',
    'about.location.description': 'Ubicado en el vibrante centro de Seattle, fácilmente accesible desde las principales autopistas',
    'about.location.button': 'Abrir en Google Maps',
    'about.testimonials.title': 'Lo Que Dicen Nuestros Clientes',
    'about.testimonials.subtitle': 'No solo tome nuestra palabra',
    'about.testimonials.testimonial1.content': 'Seattle Auto Haus hizo que comprar mi auto soñado fuera una experiencia increíble. Su equipo fue profesional, honesto y realmente se preocupó por encontrar el vehículo adecuado para mí.',
    'about.testimonials.testimonial1.author': 'Sarah Johnson',
    'about.testimonials.testimonial1.role': 'Propietaria BMW Serie 3',
    'about.testimonials.testimonial2.content': 'La calidad de los vehículos y el nivel de servicio superaron mis expectativas. He sido cliente durante años y nunca decepcionan.',
    'about.testimonials.testimonial2.author': 'Michael Chen',
    'about.testimonials.testimonial2.role': 'Propietario Mercedes Clase C',
    'about.testimonials.testimonial3.content': 'Desde la primera llamada telefónica hasta salir del lote, todo fue perfecto. Su atención al detalle y servicio al cliente no tiene igual.',
    'about.testimonials.testimonial3.author': 'David Rodriguez',
    'about.testimonials.testimonial3.role': 'Propietario Audi A4',
    // Car detail page
    'car.back': 'Volver al Inventario',
    'car.contact.title': 'Contáctenos Sobre Este Vehículo',
    'car.contact.description': '¿Interesado en este vehículo? Envíenos un mensaje y nos pondremos en contacto con usted lo antes posible.',
    'car.contact.name': 'Nombre',
    'car.contact.email': 'Correo Electrónico',
    'car.contact.phone': 'Teléfono',
    'car.contact.message': 'Mensaje',
    'car.contact.submit': 'Enviar Mensaje',
    'car.contact.success': '¡Gracias por su mensaje! Nos pondremos en contacto con usted pronto.',
    'car.specs.title': 'Especificaciones del Vehículo',
    'car.specs.vin': 'VIN',
    'car.specs.stock': 'Número de Stock',
    'car.specs.exterior': 'Color Exterior',
    'car.specs.interior': 'Color Interior',
    'car.specs.transmission': 'Transmisión',
    'car.specs.fuel': 'Tipo de Combustible',
    'car.specs.engine': 'Motor',
    'car.specs.body': 'Estilo de Carrocería',
    'car.specs.doors': 'Puertas',
    'car.specs.passengers': 'Pasajeros',
    'car.features.title': 'Características',
    'car.features.standard': 'Características Estándar',
    'car.description': 'Descripción del Vehículo',
    'car.loading': 'Cargando detalles del vehículo...',
    'car.notFound': 'Vehículo no encontrado',
    'car.notFound.description': 'El vehículo que buscas no existe.',
    'car.vehicleInformation': 'Información del Vehículo',
    'car.year': 'Año',
    'car.make': 'Marca',
    'car.model': 'Modelo',
    'car.bodyStyle': 'Estilo de Carrocería',
    'car.transmission': 'Transmisión',
    'car.fuelType': 'Tipo de Combustible',
    'car.exteriorColor': 'Color Exterior',
    'car.interiorColor': 'Color Interior',
    'car.mileage': 'millas',
    'car.interested': '¿Interesado en este vehículo?',
    'car.contactDealer': 'Contactar Concesionario',
    'car.scheduleTestDrive': 'Programar Prueba de Manejo',
    'car.getFinancing': 'Obtener Financiamiento',
    'car.performance': 'Rendimiento',
    'car.efficiency': 'Eficiencia',
    'car.dimensions': 'Dimensiones',
    'car.features': 'Características',
    'car.performanceSpecs': 'Especificaciones de Rendimiento',
    'car.horsepower': 'Caballos de Fuerza',
    'car.torque': 'Torque',
    'car.acceleration': '0-60 mph',
    'car.topSpeed': 'Velocidad Máxima',
    'car.fuelEfficiency': 'Eficiencia de Combustible',
    'car.cityMpg': 'MPG Ciudad',
    'car.highwayMpg': 'MPG Carretera',
    'car.combinedMpg': 'MPG Combinado',
    'car.fuelCapacity': 'Capacidad del Tanque de Combustible',
    'car.physicalDimensions': 'Dimensiones Físicas',
    'car.length': 'Longitud',
    'car.width': 'Ancho',
    'car.height': 'Altura',
    'car.wheelbase': 'Distancia Entre Ejes',
    'car.weight': 'Peso',
    'car.groundClearance': 'Distancia al Suelo',
    'car.featuresCapacity': 'Características y Capacidad',
    'car.cargoVolume': 'Volumen de Carga',
    'car.towingCapacity': 'Capacidad de Remolque',
    'car.additionalFeatures': 'Características Adicionales',
    'car.atRpm': '@ RPM',
    'car.lbFt': 'lb-pie',
    'car.seconds': 'segundos',
    'car.mph': 'mph',
    'car.urbanDriving': 'conducción urbana',
    'car.highwayDriving': 'conducción en carretera',
    'car.overallAverage': 'promedio general',
    'car.gallons': 'galones',
    'car.inches': 'pulgadas',
    'car.lbs': 'lbs',
    'car.cubicFeet': 'pies cúbicos',
    'car.stockNumber': 'Número de Stock',
    'car.vin': 'VIN',
    'car.doors': 'Puertas',
    'car.passengers': 'Pasajeros',
    'car.featured': 'Destacado',
    'car.newArrival': 'Nueva Llegada',
    'car.specialOffer': 'Oferta Especial',
    'language.english': 'Inglés',
    'language.spanish': 'Español',
    'language.arabic': 'Árabe',
    'language.korean': 'Coreano',
    'language.chinese': 'Chino',
    
    // Car status badges
    'car.status.featured': 'Destacado',
    'car.status.newArrival': 'Nueva Llegada',
    'car.status.specialOffer': 'Oferta Especial',
    
    // Car details
    'car.miles': 'millas',
    'car.vin': 'VIN',
    'car.stock': 'Stock',
    'car.viewDetails': 'Ver Detalles',
    
    // Home page sections
    'home.hero.title': 'Encuentra Tu Auto Perfecto',
    'home.hero.subtitle': 'Descubre vehículos de calidad con precios competitivos y servicio excepcional',
    'home.hero.browseInventory': 'Explorar Inventario',
    'home.hero.learnMore': 'Saber Más',
    'home.featured.title': 'Vehículos Destacados',
    'home.featured.subtitle': 'Nuestros vehículos más populares y mejor valorados',
    'home.featured.vehicle': 'Vehículo Destacado',
    'home.newArrivals.title': 'Nuevas Llegadas',
    'home.newArrivals.subtitle': 'Inventario fresco recién agregado a nuestro lote',
    'home.specialOffers.title': 'Ofertas Especiales',
    'home.specialOffers.subtitle': 'Ofertas por tiempo limitado y precios especiales',
    'home.contact.title': '¿Listo para Comenzar?',
    'home.contact.subtitle': 'Contáctanos hoy para programar una prueba de manejo o discutir opciones de financiamiento',
    'home.contact.callNow': 'Llamar Ahora',
    'home.contact.visitUs': 'Visítanos',
    'home.whyChoose.title': '¿Por Qué Elegir Autohaus?',
    'home.whyChoose.subtitle': 'Estamos comprometidos a brindar un servicio excepcional y vehículos de calidad',
    'home.whyChoose.quality.title': 'Vehículos de Calidad',
    'home.whyChoose.quality.description': 'Cada vehículo en nuestro inventario es cuidadosamente inspeccionado y mantenido según los más altos estándares.',
    'home.whyChoose.financing.title': 'Financiamiento Flexible',
    'home.whyChoose.financing.description': 'Trabajamos con múltiples prestamistas para encontrar las mejores opciones de financiamiento para tu presupuesto.',
    'home.whyChoose.service.title': 'Servicio Experto',
    'home.whyChoose.service.description': 'Nuestros técnicos certificados brindan servicio y mantenimiento confiable para todas las marcas y modelos.',
    
    // Navigation and UI
    'ui.scrollToSeeMore': '← Desplázate para ver más vehículos →',
    'ui.loading': 'Cargando autos...',
    'ui.previousSlide': 'Diapositiva anterior',
    'ui.nextSlide': 'Siguiente diapositiva',
    'ui.goToSlide': 'Ir a la diapositiva',
    
    // Car specs lookup
    'car.specsLookup.title': 'Búsqueda de Especificaciones del Auto',
    'car.specsLookup.vinLabel': 'Número VIN',
    'car.specsLookup.vinPlaceholder': 'Ingrese VIN de 17 caracteres',
    'car.specsLookup.searching': 'Buscando...',
    'car.specsLookup.lookup': 'Buscar',
    'car.specsLookup.description': 'Ingrese el Número de Identificación del Vehículo de 17 caracteres para buscar especificaciones detalladas',
    'car.specsLookup.invalidVin': 'VIN Inválido',
    'car.specsLookup.invalidVinDescription': 'Por favor ingrese un VIN válido de 17 caracteres',
    'car.specsLookup.specsFound': 'Especificaciones Encontradas',
    'car.specsLookup.specsFoundFor': 'Especificaciones encontradas para',
    'car.specsLookup.noSpecsFound': 'No se encontraron especificaciones para este VIN',
    'car.specsLookup.lookupFailed': 'Búsqueda de Especificaciones Falló',
    'car.specsLookup.unknownError': 'Error desconocido ocurrió',
    
    'common.loading': 'Cargando...',
    'common.search': 'Buscar',
    'common.searching': 'Buscando...',
    'common.selected': 'Seleccionado',
    'common.features': 'Características',
    'common.quickActions': 'Acciones Rápidas',
    'common.filters': 'Filtros',
    'common.sortBy': 'Ordenar Por',
    'common.priceRange': 'Rango de Precio',
    'common.yearRange': 'Rango de Año',
    'common.clearFilters': 'Limpiar Filtros',
    'common.apply': 'Aplicar',
    'common.cancel': 'Cancelar',
    'common.save': 'Guardar',
    'common.edit': 'Editar',
    'common.delete': 'Eliminar',
    'common.view': 'Ver',
    'common.details': 'Detalles',
    'common.close': 'Cerrar',
    'common.back': 'Atrás',
    'common.next': 'Siguiente',
    'common.previous': 'Anterior',
    'common.more': 'Más',
    'common.less': 'Menos',
    'common.all': 'Todo',
    'common.none': 'Ninguno',
    'common.yes': 'Sí',
    'common.no': 'No',
    'common.ok': 'OK',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.warning': 'Advertencia',
    'common.info': 'Información',
    'common.services': 'Servicios',
    'common.support': 'Soporte',
    'common.hoverToShow': 'Pasa el cursor cerca del borde izquierdo para mostrar/ocultar',
    'common.quickAccess': 'Acceso rápido a herramientas y servicios',
  },
  ar: {
    'header.title': 'سياتل أوتو هاوس',
    'header.subtitle': 'وكالة سيارات فاخرة',
    'nav.home': 'الرئيسية',
    'nav.inventory': 'المخزون',
    'nav.about': 'حول',
    'settings.language': 'اللغة',
    'settings.darkMode': 'الوضع المظلم',
    'settings.lightMode': 'الوضع المضيء',
    'settings.system': 'النظام',
    'settings.theme': 'المظهر',
    'settings.help': 'المساعدة',
    'hero.title': 'اعثر على سيارتك المثالية',
    'hero.subtitle': 'اكتشف مجموعتنا المميزة من السيارات الفاخرة والأداء العالي مع البحث الفوري والنتائج في الوقت الفعلي',
    'stats.vehicles': 'سيارات في المخزون',
    'stats.brands': 'العلامات التجارية المتاحة',
    'stats.satisfaction': 'رضا العملاء',
    'search.title': 'ابحث في مخزوننا',
    'search.placeholder': 'ابحث بالعلامة التجارية أو النموذج أو السنة أو السعر أو الميزات...',
    'search.button': 'البحث في المخزون',
    'search.recent': 'البحث الأخير',
    'search.popular': 'البحث الشائع',
    'search.quickResults': 'النتائج السريعة',
    'featured.title': 'السيارات المميزة',
    'featured.subtitle': 'سيارات مختارة من مجموعتنا المميزة',
    'featured.viewAll': 'عرض جميع السيارات',
    'testimonials.title': 'ماذا يقول عملاؤنا',
    'testimonials.subtitle': 'تجارب حقيقية من عملاء راضين',
    'footer.description': 'وكالة سيارات فاخرة تخدم منطقة سياتل الكبرى',
    'footer.privacy': 'سياسة الخصوصية',
    'footer.terms': 'شروط الخدمة',
    'footer.contact': 'اتصل بنا',
    'inventory.title': 'مخزون السيارات',
    'inventory.subtitle': 'تصفح مجموعتنا الكاملة من السيارات',
    'inventory.searchResults': 'نتائج البحث عن',
    'inventory.filters': 'المرشحات',
    'inventory.sortBy': 'ترتيب حسب',
    'inventory.priceRange': 'نطاق السعر',
    'inventory.yearRange': 'نطاق السنة',
    'inventory.clearFilters': 'مسح المرشحات',
    'inventory.searching': 'البحث في المخزون...',
    'inventory.noResults': 'لم يتم العثور على سيارات',
    'inventory.tryAdjusting': 'حاول تعديل مصطلحات البحث أو المرشحات',
    'inventory.clearSearch': 'مسح البحث',
    'inventory.searchPrompt': 'البحث عن السيارات',
    'inventory.searchPromptSubtitle': 'استخدم شريط البحث أعلاه للعثور على السيارات في مخزوننا',
    'inventory.showing': 'عرض',
    'inventory.of': 'من',
    'inventory.vehicles': 'سيارات',
    'inventory.for': 'ل',
    'inventory.viewDetails': 'عرض التفاصيل',
    'inventory.previous': 'السابق',
    'inventory.next': 'التالي',
    'inventory.page': 'الصفحة',
    'inventory.featured': 'المركبات المميزة',
    'inventory.newArrivals': 'الوافدون الجدد',
    'inventory.specialOffers': 'العروض الخاصة',
    'inventory.recentlyViewed': 'المشاهدون مؤخراً',
    // Additional inventory keys needed by the page
    'inventory.ourInventory': 'مخزوننا',
    'inventory.browseExtensive': 'تصفح مجموعتنا الواسعة من المركبات عالية الجودة',
    'inventory.searchCars': 'البحث عن السيارات...',
    'inventory.make': 'الماركة',
    'inventory.allMakes': 'جميع الماركات',
    'inventory.allBodyStyles': 'جميع أنماط الهيكل',
    'inventory.allPrices': 'جميع الأسعار',
    'inventory.under20000': 'أقل من $20,000',
    'inventory.price20000to40000': '$20,000 - $40,000',
    'inventory.price40000to60000': '$40,000 - $60,000',
    'inventory.price60000to80000': '$60,000 - $80,000',
    'inventory.price80000plus': '$80,000+',
    'inventory.year': 'السنة',
    'inventory.allYears': 'جميع السنوات',
    'inventory.noVehiclesFound': 'لم يتم العثور على مركبات',
    'inventory.tryAdjustingCriteria': 'حاول تعديل معايير البحث أو المرشحات',
    'inventory.clearAllFilters': 'مسح جميع المرشحات',
    'inventory.cantFind': 'لا تستطيع العثور على ما تبحث عنه؟',
    'inventory.contactUsHelp': 'اتصل بنا وسنساعدك في العثور على المركبة المثالية',
    'inventory.contactUs': 'اتصل بنا',
    'inventory.scheduleTestDrive': 'جدولة اختبار القيادة',
    'inventory.loading': 'جاري تحميل المخزون...',
    // Search section (home page & inventory)
    'search.title': 'البحث عن المركبات',
    'search.subtitle': 'اعثر على مركبتك المثالية',
    'search.placeholder': 'البحث بالماركة، النموذج، السنة، السعر أو الميزات...',
    'search.button': 'البحث',
    'search.quickResults': 'النتائج السريعة',
    'search.recent': 'البحث الأخير',
    'search.popular': 'البحث الشائع',
    // About page
    'about.hero.title': 'عن سياتل أوتو هاوس',
    'about.hero.subtitle': 'شريكك الموثوق للعثور على المركبة المثالية. لقد كنا نخدم منطقة سياتل الحضرية بمركبات فاخرة وخدمة استثنائية لأكثر من عقدين.',
    'about.stats.vehicles': 'المركبات في المخزون',
    'about.stats.customers': 'العملاء الراضون',
    'about.stats.experience': 'سنوات الخبرة',
    'about.stats.rating': 'تقييم العملاء',
    'about.story.title': 'قصتنا',
    'about.story.p1': 'تأسست في عام 1999، بدأت سياتل أوتو هاوس كمعرض عائلي صغير بمهمة بسيطة: توفير مركبات بأعلى جودة مع أكثر خدمة شفافة وصادقة في الصناعة.',
    'about.story.p2': 'على مر السنين، نما ليكون أحد أكثر الأسماء موثوقية في سوق السيارات في سياتل، متخصصاً في مركبات الفخامة والأداء مع الحفاظ على التزامنا برضا العملاء.',
    'about.story.p3': 'فريقنا من الفنيين المعتمدين ومحترفي المبيعات شغوفون بالسيارات ومكرسون لمساعدتك في العثور على المركبة المثالية التي تناسب نمط حياتك وميزانيتك.',
    'about.values.title': 'قيمنا',
    'about.values.subtitle': 'المبادئ التي توجه كل ما نقوم به',
    'about.values.trust.title': 'الثقة والشفافية',
    'about.values.trust.description': 'نؤمن بالشفافية الكاملة في جميع معاملاتنا، من الأسعار إلى تاريخ المركبة.',
    'about.values.quality.title': 'الجودة والتميز',
    'about.values.quality.description': 'كل مركبة في مخزوننا تلبي معايير الجودة الصارمة وعملية الفحص الشاملة.',
    'about.values.customer.title': 'العميل أولاً',
    'about.values.customer.description': 'رضاك هو أولويتنا. نحن هنا لمساعدتك في العثور على المركبة المثالية.',
    'about.contact.title': 'تواصل معنا',
    'about.contact.subtitle': 'هل لديك أسئلة؟ نود أن نسمع منك.',
    'about.contact.form.title': 'أرسل لنا رسالة',
    'about.contact.form.description': 'املأ النموذج أدناه وسنتواصل معك في أقرب وقت ممكن.',
    'about.contact.form.name': 'الاسم',
    'about.contact.form.email': 'البريد الإلكتروني',
    'about.contact.form.phone': 'الهاتف',
    'about.contact.form.message': 'الرسالة',
    'about.contact.form.submit': 'إرسال الرسالة',
    'about.contact.info.title': 'معلومات الاتصال',
    'about.contact.info.address': 'العنوان',
    'about.contact.info.address.value': '1234 أوتو درايف<br />سياتل، واشنطن 98101',
    'about.contact.info.phone': 'الهاتف',
    'about.contact.info.phone.value': '(206) 555-0123<br />(206) 555-0124',
    'about.contact.info.email': 'البريد الإلكتروني',
    'about.contact.info.email.value': 'info@seattleautohaus.com<br />sales@seattleautohaus.com',
    'about.contact.info.hours': 'ساعات العمل',
    'about.contact.info.hours.value': 'الاثنين - الجمعة: 9:00 ص - 8:00 م<br />السبت: 9:00 ص - 6:00 م<br />الأحد: 11:00 ص - 5:00 م',
    'about.contact.social.title': 'تابعنا',
    'about.contact.social.facebook': 'فيسبوك',
    'about.contact.social.twitter': 'تويتر',
    'about.contact.social.instagram': 'إنستغرام',
    'about.contact.social.linkedin': 'لينكد إن',
    'about.location.title': 'اعثر علينا',
    'about.location.subtitle': 'زر معرضنا في قلب سياتل',
    'about.location.description': 'يقع في وسط سياتل النابض بالحياة، يمكن الوصول إليه بسهولة من الطرق السريعة الرئيسية',
    'about.location.button': 'فتح في خرائط جوجل',
    'about.testimonials.title': 'ماذا يقول عملاؤنا',
    'about.testimonials.subtitle': 'لا تأخذ كلمتنا فقط',
    'about.testimonials.testimonial1.content': 'جعلت سياتل أوتو هاوس شراء سيارتي الحلم تجربة مذهلة. فريقهم كان محترفاً وصادقاً واهتم حقاً بالعثور على المركبة المناسبة لي.',
    'about.testimonials.testimonial1.author': 'سارة جونسون',
    'about.testimonials.testimonial1.role': 'مالكة بي إم دبليو سلسلة 3',
    'about.testimonials.testimonial2.content': 'جودة المركبات ومستوى الخدمة تجاوزت توقعاتي. لقد كنت عميلاً لسنوات ولا يخيبون أبداً.',
    'about.testimonials.testimonial2.author': 'مايكل تشين',
    'about.testimonials.testimonial2.role': 'مالك مرسيدس فئة C',
    'about.testimonials.testimonial3.content': 'من أول مكالمة هاتفية حتى الخروج من المعرض، كل شيء كان مثالياً. انتباههم للتفاصيل وخدمة العملاء لا مثيل لها.',
    'about.testimonials.testimonial3.author': 'ديفيد رودريغيز',
    'about.testimonials.testimonial3.role': 'مالك أودي A4',
    // Car detail page
    'car.back': 'العودة إلى المخزون',
    'car.contact.title': 'اتصل بنا حول هذه المركبة',
    'car.contact.description': 'مهتم بهذه المركبة؟ أرسل لنا رسالة وسنتواصل معك في أقرب وقت ممكن.',
    'car.contact.name': 'الاسم',
    'car.contact.email': 'البريد الإلكتروني',
    'car.contact.phone': 'الهاتف',
    'car.contact.message': 'الرسالة',
    'car.contact.submit': 'إرسال الرسالة',
    'car.contact.success': 'شكراً لك على رسالتك! سنتواصل معك قريباً.',
    'car.specs.title': 'مواصفات المركبة',
    'car.specs.vin': 'VIN',
    'car.specs.stock': 'رقم المخزون',
    'car.specs.exterior': 'اللون الخارجي',
    'car.specs.interior': 'اللون الداخلي',
    'car.specs.transmission': 'ناقل الحركة',
    'car.specs.fuel': 'نوع الوقود',
    'car.specs.engine': 'المحرك',
    'car.specs.body': 'نمط الهيكل',
    'car.specs.doors': 'الأبواب',
    'car.specs.passengers': 'الركاب',
    'car.features.title': 'الميزات',
    'car.features.standard': 'الميزات القياسية',
    'car.description': 'وصف المركبة',
    'car.loading': 'جاري تحميل تفاصيل المركبة...',
    'car.notFound': 'لم يتم العثور على المركبة',
    'car.notFound.description': 'المركبة التي تبحث عنها غير موجودة.',
    'car.vehicleInformation': 'معلومات المركبة',
    'car.year': 'السنة',
    'car.make': 'الماركة',
    'car.model': 'النموذج',
    'car.bodyStyle': 'نمط الهيكل',
    'car.transmission': 'ناقل الحركة',
    'car.fuelType': 'نوع الوقود',
    'car.exteriorColor': 'اللون الخارجي',
    'car.interiorColor': 'اللون الداخلي',
    'car.mileage': 'أميال',
    'car.interested': 'مهتم بهذه المركبة؟',
    'car.contactDealer': 'اتصل بالوكيل',
    'car.scheduleTestDrive': 'جدولة اختبار القيادة',
    'car.getFinancing': 'الحصول على التمويل',
    'car.performance': 'الأداء',
    'car.efficiency': 'الكفاءة',
    'car.dimensions': 'الأبعاد',
    'car.features': 'الميزات',
    'car.performanceSpecs': 'مواصفات الأداء',
    'car.horsepower': 'حصان',
    'car.torque': 'عزم الدوران',
    'car.acceleration': '0-60 ميل في الساعة',
    'car.topSpeed': 'السرعة القصوى',
    'car.fuelEfficiency': 'كفاءة الوقود',
    'car.cityMpg': 'ميل للغالون في المدينة',
    'car.highwayMpg': 'ميل للغالون على الطريق السريع',
    'car.combinedMpg': 'ميل للغالون مجتمع',
    'car.fuelCapacity': 'سعة خزان الوقود',
    'car.physicalDimensions': 'الأبعاد المادية',
    'car.length': 'الطول',
    'car.width': 'العرض',
    'car.height': 'الارتفاع',
    'car.wheelbase': 'المسافة بين المحاور',
    'car.weight': 'الوزن',
    'car.groundClearance': 'المسافة من الأرض',
    'car.featuresCapacity': 'الميزات والسعة',
    'car.cargoVolume': 'حجم الشحن',
    'car.towingCapacity': 'قدرة السحب',
    'car.additionalFeatures': 'الميزات الإضافية',
    'car.atRpm': '@ دورة في الدقيقة',
    'car.lbFt': 'رطل-قدم',
    'car.seconds': 'ثواني',
    'car.mph': 'ميل في الساعة',
    'car.urbanDriving': 'القيادة في المدينة',
    'car.highwayDriving': 'القيادة على الطريق السريع',
    'car.overallAverage': 'المتوسط العام',
    'car.gallons': 'غالونات',
    'car.inches': 'بوصات',
    'car.lbs': 'رطل',
    'car.cubicFeet': 'قدم مكعب',
    'car.stockNumber': 'رقم المخزون',
    'car.vin': 'VIN',
    'car.doors': 'الأبواب',
    'car.passengers': 'الركاب',
    'car.featured': 'مميز',
    'car.newArrival': 'وافد جديد',
    'car.specialOffer': 'عرض خاص',
    'language.english': 'الإنجليزية',
    'language.spanish': 'الإسبانية',
    'language.arabic': 'العربية',
    'language.korean': 'الكورية',
    'language.chinese': 'الصينية',
    
    // Car status badges
    'car.status.featured': 'مميز',
    'car.status.newArrival': 'وافد جديد',
    'car.status.specialOffer': 'عرض خاص',
    
    // Car details
    'car.miles': 'millas',
    'car.stock': 'Stock',
    'car.viewDetails': 'Ver Detalles',
    
    // Home page sections
    'home.hero.title': 'Encuentra Tu Auto Perfecto',
    'home.hero.subtitle': 'Descubre vehículos de calidad con precios competitivos y servicio excepcional',
    'home.hero.browseInventory': 'Explorar Inventario',
    'home.hero.learnMore': 'Saber Más',
    'home.featured.title': 'Vehículos Destacados',
    'home.featured.subtitle': 'Nuestros vehículos más populares y mejor valorados',
    'home.featured.vehicle': 'Vehículo Destacado',
    'home.newArrivals.title': 'Nuevas Llegadas',
    'home.newArrivals.subtitle': 'Inventario fresco recién agregado a nuestro lote',
    'home.specialOffers.title': 'Ofertas Especiales',
    'home.specialOffers.subtitle': 'Ofertas por tiempo limitado y precios especiales',
    'home.contact.title': '¿Listo para Comenzar?',
    'home.contact.subtitle': 'Contáctanos hoy para programar una prueba de manejo o discutir opciones de financiamiento',
    'home.contact.callNow': 'Llamar Ahora',
    'home.contact.visitUs': 'Visítanos',
    'home.whyChoose.title': '¿Por Qué Elegir Autohaus?',
    'home.whyChoose.subtitle': 'Estamos comprometidos a brindar un servicio excepcional y vehículos de calidad',
    'home.whyChoose.quality.title': 'Vehículos de Calidad',
    'home.whyChoose.quality.description': 'Cada vehículo en nuestro inventario es cuidadosamente inspeccionado y mantenido según los más altos estándares.',
    'home.whyChoose.financing.title': 'Financiamiento Flexible',
    'home.whyChoose.financing.description': 'Trabajamos con múltiples prestamistas para encontrar las mejores opciones de financiamiento para tu presupuesto.',
    'home.whyChoose.service.title': 'Servicio Experto',
    'home.whyChoose.service.description': 'Nuestros técnicos certificados brindan servicio y mantenimiento confiable para todas las marcas y modelos.',
    
    // Navigation and UI
    'ui.scrollToSeeMore': '← Desplázate para ver más vehículos →',
    'ui.loading': 'Cargando vehículos...',
    'ui.previousSlide': 'Diapositiva anterior',
    'ui.nextSlide': 'Siguiente diapositiva',
    'ui.goToSlide': 'Ir a diapositiva',
    
    'common.loading': 'Cargando...',
    'common.search': 'Buscar',
    'common.searching': 'Buscando...',
    'common.selected': 'Seleccionado',
  },
  ko: {
    'header.title': '시애틀 오토 하우스',
    'header.subtitle': '프리미엄 자동차 딜러십',
    'nav.home': '홈',
    'nav.inventory': '재고',
    'nav.about': '소개',
    'settings.language': '언어',
    'settings.darkMode': '다크 모드',
    'settings.lightMode': '라이트 모드',
    'settings.help': '도움말',
    'hero.title': '완벽한 차를 찾으세요',
    'hero.subtitle': '즉시 검색과 실시간 결과로 럭셔리 및 고성능 차량의 프리미엄 선택을 발견하세요',
    'stats.vehicles': '재고 차량',
    'stats.brands': '사용 가능한 브랜드',
    'stats.satisfaction': '고객 만족도',
    'search.title': '재고 검색',
    'search.placeholder': '브랜드, 모델, 연도, 가격 또는 기능으로 검색...',
    'search.button': '재고 검색',
    'search.recent': '최근 검색',
    'search.popular': '인기 검색',
    'search.quickResults': '빠른 결과',
    'featured.title': '추천 차량',
    'featured.subtitle': '프리미엄 컬렉션에서 선별된 차량',
    'featured.viewAll': '모든 차량 보기',
    'testimonials.title': '고객들의 후기',
    'testimonials.subtitle': '만족한 고객들의 실제 경험',
    'footer.description': '시애틀 대도시 지역을 서비스하는 프리미엄 자동차 딜러십',
    'footer.privacy': '개인정보 보호정책',
    'footer.terms': '서비스 약관',
    'footer.contact': '문의하기',
    'inventory.title': '차량 재고',
    'inventory.subtitle': '완전한 차량 선택을 둘러보세요',
    'inventory.searchResults': '검색 결과',
    'inventory.filters': '필터',
    'inventory.sortBy': '정렬 기준',
    'inventory.priceRange': '가격 범위',
    'inventory.yearRange': '연도 범위',
    'inventory.clearFilters': '필터 지우기',
    'inventory.searching': '재고 검색 중...',
    'inventory.noResults': '차량을 찾을 수 없습니다',
    'inventory.tryAdjusting': '검색어나 필터를 조정해 보세요',
    'inventory.clearSearch': '검색 지우기',
    'inventory.searchPrompt': '차량 검색',
    'inventory.searchPromptSubtitle': '위의 검색창을 사용하여 재고에서 차량을 찾으세요',
    'inventory.showing': '표시',
    'inventory.of': '중',
    'inventory.vehicles': '대의 차량',
    'inventory.for': '에 대한',
    'inventory.viewDetails': '상세 보기',
    'inventory.previous': '이전',
    'inventory.next': '다음',
    'inventory.page': '페이지',
    'inventory.featured': '精选车辆',
    'inventory.newArrivals': '新到货',
    'inventory.specialOffers': '特别优惠',
    'inventory.recentlyViewed': '最近浏览',
    'inventory.bodyStyle': '车身样式',
    'inventory.fuelType': '燃料类型',
    'inventory.financing': '融资',
    'inventory.tradeIn': '以旧换新',
    'inventory.warranty': '保修',
    'inventory.maintenance': '保养',
    'inventory.liveChat': '在线客服',
    'inventory.phoneSupport': '电话支持',
    'inventory.emailSupport': '电子邮件支持',
    'inventory.faq': '常见问题',
    'language.english': '영어',
    'language.spanish': '스페인어',
    'language.arabic': '아랍어',
    'language.korean': '한국어',
    'language.chinese': '중국어',
    
    // Car status badges
    'car.status.featured': '추천',
    'car.status.newArrival': '신규 입고',
    'car.status.specialOffer': '특별 할인',
    
    // Car details
    'car.miles': '마일',
    'car.vin': 'VIN',
    'car.stock': '재고',
    'car.viewDetails': '상세 보기',
    
    // Home page sections
    'home.hero.title': '완벽한 차를 찾으세요',
    'home.hero.subtitle': '경쟁력 있는 가격과 뛰어난 서비스로 품질 좋은 차량을 발견하세요',
    'home.hero.browseInventory': '재고 둘러보기',
    'home.hero.learnMore': '더 알아보기',
    'home.featured.title': '추천 차량',
    'home.featured.subtitle': '가장 인기 있고 높은 평가를 받은 차량들',
    'home.newArrivals.title': '신규 입고',
    'home.newArrivals.subtitle': '최근에 추가된 새로운 재고',
    'home.specialOffers.title': '특별 할인',
    'home.specialOffers.subtitle': '한정 시간 할인과 특별 가격',
    'home.contact.title': '시작할 준비가 되셨나요?',
    'home.contact.subtitle': '시승 예약이나 금융 옵션에 대해 논의하려면 오늘 연락하세요',
    'home.contact.callNow': '지금 전화',
    'home.contact.visitUs': '방문하기',
    'home.whyChoose.title': '왜 오토하우스를 선택해야 할까요?',
    'home.whyChoose.subtitle': '우리는 뛰어난 서비스와 품질 좋은 차량을 제공하기 위해 노력합니다',
    'home.whyChoose.quality.title': '품질 좋은 차량',
    'home.whyChoose.quality.description': '재고의 모든 차량은 최고의 기준에 따라 신중하게 검사되고 유지보수됩니다.',
    'home.whyChoose.financing.title': '유연한 금융',
    'home.whyChoose.financing.description': '예산에 맞는 최고의 금융 옵션을 찾기 위해 여러 대출 기관과 협력합니다.',
    'home.whyChoose.service.title': '전문 서비스',
    'home.whyChoose.service.description': '우리의 인증된 기술자들은 모든 브랜드와 모델에 대해 신뢰할 수 있는 서비스와 유지보수를 제공합니다.',
    
    // Navigation and UI
    'ui.scrollToSeeMore': '← 더 많은 차량을 보려면 스크롤하세요 →',
    'ui.loading': '차량 로딩 중...',
    'ui.previousSlide': '이전 슬라이드',
    'ui.nextSlide': '다음 슬라이드',
    'ui.goToSlide': '슬라이드로 이동',
    
    'common.loading': '로딩 중...',
    'common.search': '검색',
    'common.searching': '검색 중...',
    'common.selected': '선택됨',
    // Car detail page
    'car.loading': '차량 상세 정보 로딩 중...',
    'car.notFound': '차량을 찾을 수 없습니다',
    'car.notFound.description': '찾고 계신 차량이 존재하지 않습니다.',
    'car.vehicleInformation': '차량 정보',
    'car.year': '연도',
    'car.make': '제조사',
    'car.model': '모델',
    'car.bodyStyle': '바디 스타일',
    'car.transmission': '변속기',
    'car.fuelType': '연료 타입',
    'car.exteriorColor': '외장 색상',
    'car.interiorColor': '내장 색상',
    'car.mileage': '마일',
    'car.interested': '이 차량에 관심이 있으신가요?',
    'car.contactDealer': '딜러에게 문의',
    'car.scheduleTestDrive': '시승 예약',
    'car.getFinancing': '금융 상담',
    'car.performance': '성능',
    'car.efficiency': '효율성',
    'car.dimensions': '치수',
    'car.features': '기능',
    'car.performanceSpecs': '성능 사양',
    'car.horsepower': '마력',
    'car.torque': '토크',
    'car.acceleration': '0-60 mph',
    'car.topSpeed': '최고 속도',
    'car.fuelEfficiency': '연료 효율성',
    'car.cityMpg': '도시 MPG',
    'car.highwayMpg': '고속도로 MPG',
    'car.combinedMpg': '복합 MPG',
    'car.fuelCapacity': '연료 탱크 용량',
    'car.physicalDimensions': '물리적 치수',
    'car.length': '길이',
    'car.width': '너비',
    'car.height': '높이',
    'car.wheelbase': '휠베이스',
    'car.weight': '무게',
    'car.groundClearance': '지상고',
    'car.featuresCapacity': '기능 및 용량',
    'car.cargoVolume': '적재 용량',
    'car.towingCapacity': '견인 용량',
    'car.additionalFeatures': '추가 기능',
    'car.atRpm': '@ RPM',
    'car.lbFt': 'lb-ft',
    'car.seconds': '초',
    'car.mph': 'mph',
    'car.urbanDriving': '도시 주행',
    'car.highwayDriving': '고속도로 주행',
    'car.overallAverage': '전체 평균',
    'car.gallons': '갤런',
    'car.inches': '인치',
    'car.lbs': '파운드',
    'car.cubicFeet': '입방 피트',
    'car.stockNumber': '재고 번호',
    'car.vin': 'VIN',
    'car.doors': '문',
    'car.passengers': '승객',
    'car.featured': '추천',
    'car.newArrival': '신규 입고',
    'car.specialOffer': '특별 할인',
  },
  zh: {
    'header.title': '西雅图汽车之家',
    'header.subtitle': '高端汽车经销商',
    'nav.home': '首页',
    'nav.inventory': '库存',
    'nav.about': '关于',
    'settings.language': '语言',
    'settings.darkMode': '深色模式',
    'settings.lightMode': '浅色模式',
    'settings.help': '帮助',
    'hero.title': '找到您的完美座驾',
    'hero.subtitle': '通过即时搜索和实时结果发现我们精选的豪华和高性能汽车',
    'stats.vehicles': '库存车辆',
    'stats.brands': '可用品牌',
    'stats.satisfaction': '客户满意度',
    'search.title': '搜索我们的库存',
    'search.placeholder': '按品牌、型号、年份、价格或功能搜索...',
    'search.button': '搜索库存',
    'search.recent': '最近搜索',
    'search.popular': '热门搜索',
    'search.quickResults': '快速结果',
    'featured.title': '精选车辆',
    'featured.subtitle': '从我们高端系列中精心挑选的车辆',
    'featured.viewAll': '查看所有车辆',
    'testimonials.title': '客户评价',
    'testimonials.subtitle': '满意客户的真实体验',
    'footer.description': '为西雅图大都会区服务的高端汽车经销商',
    'footer.privacy': '隐私政策',
    'footer.terms': '服务条款',
    'footer.contact': '联系我们',
    'inventory.title': '车辆库存',
    'inventory.subtitle': '浏览我们完整的车辆选择',
    'inventory.searchResults': '搜索结果',
    'inventory.filters': '筛选器',
    'inventory.sortBy': '排序方式',
    'inventory.priceRange': '价格范围',
    'inventory.yearRange': '年份范围',
    'inventory.clearFilters': '清除筛选器',
    'inventory.searching': '搜索库存中...',
    'inventory.noResults': '未找到车辆',
    'inventory.tryAdjusting': '尝试调整搜索词或筛选器',
    'inventory.clearSearch': '清除搜索',
    'inventory.searchPrompt': '搜索车辆',
    'inventory.searchPromptSubtitle': '使用上方的搜索栏在库存中查找车辆',
    'inventory.showing': '显示',
    'inventory.of': '共',
    'inventory.vehicles': '辆车',
    'inventory.for': '的',
    'inventory.viewDetails': '查看详情',
    'inventory.previous': '上一页',
    'inventory.next': '下一页',
    'inventory.page': '页',
    'inventory.featured': '精选车辆',
    'inventory.newArrivals': '新到货',
    'inventory.specialOffers': '特别优惠',
    'inventory.recentlyViewed': '最近浏览',
    'inventory.bodyStyle': '车身样式',
    'inventory.fuelType': '燃料类型',
    'inventory.financing': '融资',
    'inventory.tradeIn': '以旧换新',
    'inventory.warranty': '保修',
    'inventory.maintenance': '保养',
    'inventory.liveChat': '在线客服',
    'inventory.phoneSupport': '电话支持',
    'inventory.emailSupport': '电子邮件支持',
    'inventory.faq': '常见问题',
    'language.english': '英语',
    'language.spanish': '西班牙语',
    'language.arabic': '阿拉伯语',
    'language.korean': '韩语',
    'language.chinese': '中文',
    
    // Car status badges
    'car.status.featured': '精选',
    'car.status.newArrival': '新到货',
    'car.status.specialOffer': '特别优惠',
    
    // Car details
    'car.miles': '英里',
    'car.vin': 'VIN',
    'car.stock': '库存',
    'car.viewDetails': '查看详情',
    
    // Home page sections
    'home.hero.title': '找到您的完美座驾',
    'home.hero.subtitle': '发现具有竞争价格和卓越服务的优质车辆',
    'home.hero.browseInventory': '浏览库存',
    'home.hero.learnMore': '了解更多',
    'home.featured.title': '精选车辆',
    'home.featured.subtitle': '我们最受欢迎和评价最高的车辆',
    'home.newArrivals.title': '新到货',
    'home.newArrivals.subtitle': '刚刚添加到我们场地的全新库存',
    'home.specialOffers.title': '特别优惠',
    'home.specialOffers.subtitle': '限时优惠和特别定价',
    'home.contact.title': '准备开始了吗？',
    'home.contact.subtitle': '今天就联系我们安排试驾或讨论融资选择',
    'home.contact.callNow': '立即致电',
    'home.contact.visitUs': '访问我们',
    'home.whyChoose.title': '为什么选择汽车之家？',
    'home.whyChoose.subtitle': '我们致力于提供卓越的服务和优质车辆',
    'home.whyChoose.quality.title': '优质车辆',
    'home.whyChoose.quality.description': '我们库存中的每辆车都经过仔细检查并按照最高标准维护。',
    'home.whyChoose.financing.title': '灵活融资',
    'home.whyChoose.financing.description': '我们与多家贷款机构合作，为您的预算找到最佳融资选择。',
    'home.whyChoose.service.title': '专业服务',
    'home.whyChoose.service.description': '我们的认证技术人员为所有品牌和型号提供可靠的服务和维护。',
    
    // Navigation and UI
    'ui.scrollToSeeMore': '← 滚动查看更多车辆 →',
    'ui.loading': '正在加载车辆...',
    'ui.previousSlide': '上一张幻灯片',
    'ui.nextSlide': '下一张幻灯片',
    'ui.goToSlide': '转到幻灯片',
    
    'common.loading': '加载中...',
    'common.search': '搜索',
    'common.searching': '搜索中...',
    'common.selected': '已选择',
    // Car detail page
    'car.loading': '正在加载车辆详情...',
    'car.notFound': '未找到车辆',
    'car.notFound.description': '您要查找的车辆不存在。',
    'car.vehicleInformation': '车辆信息',
    'car.year': '年份',
    'car.make': '品牌',
    'car.model': '型号',
    'car.bodyStyle': '车身样式',
    'car.transmission': '变速箱',
    'car.fuelType': '燃料类型',
    'car.exteriorColor': '外观颜色',
    'car.interiorColor': '内饰颜色',
    'car.mileage': '英里',
    'car.interested': '对这辆车感兴趣吗？',
    'car.contactDealer': '联系经销商',
    'car.scheduleTestDrive': '安排试驾',
    'car.getFinancing': '获取融资',
    'car.performance': '性能',
    'car.efficiency': '效率',
    'car.dimensions': '尺寸',
    'car.features': '功能',
    'car.performanceSpecs': '性能规格',
    'car.horsepower': '马力',
    'car.torque': '扭矩',
    'car.acceleration': '0-60 mph',
    'car.topSpeed': '最高速度',
    'car.fuelEfficiency': '燃油效率',
    'car.cityMpg': '城市 MPG',
    'car.highwayMpg': '高速公路 MPG',
    'car.combinedMpg': '综合 MPG',
    'car.fuelCapacity': '燃油箱容量',
    'car.physicalDimensions': '物理尺寸',
    'car.length': '长度',
    'car.width': '宽度',
    'car.height': '高度',
    'car.wheelbase': '轴距',
    'car.weight': '重量',
    'car.groundClearance': '离地间隙',
    'car.featuresCapacity': '功能和容量',
    'car.cargoVolume': '载货容积',
    'car.towingCapacity': '牵引能力',
    'car.additionalFeatures': '附加功能',
    'car.atRpm': '@ RPM',
    'car.lbFt': 'lb-ft',
    'car.seconds': '秒',
    'car.mph': 'mph',
    'car.urbanDriving': '城市驾驶',
    'car.highwayDriving': '高速公路驾驶',
    'car.overallAverage': '整体平均',
    'car.gallons': '加仑',
    'car.inches': '英寸',
    'car.lbs': '磅',
    'car.cubicFeet': '立方英尺',
    'car.stockNumber': '库存编号',
    'car.vin': 'VIN',
    'car.doors': '车门',
    'car.passengers': '乘客',
    'car.featured': '精选',
    'car.newArrival': '新到货',
    'car.specialOffer': '特别优惠',
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');
  const [isInitialized, setIsInitialized] = useState(false);

  // Function to detect browser language and map to supported languages
  const detectBrowserLanguage = (): Language => {
    if (typeof window === 'undefined') return 'en';
    
    const browserLang = navigator.language.toLowerCase();
    
    // Map browser languages to our supported languages
    if (browserLang.startsWith('es') || browserLang.startsWith('es-')) {
      return 'es';
    } else if (browserLang.startsWith('ar') || browserLang.startsWith('ar-')) {
      return 'ar';
    } else if (browserLang.startsWith('ko') || browserLang.startsWith('ko-')) {
      return 'ko';
    } else if (browserLang.startsWith('zh') || browserLang.startsWith('zh-')) {
      return 'zh';
    }
    
    return 'en';
  };

  // Load language from localStorage or detect from browser on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem('selectedLanguage') as Language;
    let initialLanguage: Language = 'en';
    
    if (savedLanguage && ['en', 'es', 'ar', 'ko', 'zh'].includes(savedLanguage)) {
      initialLanguage = savedLanguage;
    } else {
      // Auto-detect language from browser if no saved preference
      initialLanguage = detectBrowserLanguage();
      localStorage.setItem('selectedLanguage', initialLanguage);
    }
    
    // Set the language state
    setLanguage(initialLanguage);
    setIsInitialized(true);
  }, []);

  // Save language to localStorage when it changes
  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('selectedLanguage', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  // Don't render until language is initialized to prevent hydration mismatch
  if (!isInitialized) {
    return null;
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
