import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const carData = [
  {
    make: 'BMW',
    model: '3 Series',
    year: 2023,
    price: 45990,
    mileage: 15000,
    description: 'Luxury sedan with excellent condition and full service history.',
    exteriorColor: 'Alpine White',
    interiorColor: 'Black Leather',
    transmission: '8-Speed Automatic',
    fuelType: 'Gasoline',
    engine: '2.0L Turbo I4',
    bodyStyle: 'Sedan',
    doors: 4,
    passengers: 5,
    features: ['Sunroof', 'Navigation', 'Leather Seats', 'Bluetooth', 'Backup Camera']
  },
  {
    make: 'Mercedes-Benz',
    model: 'C-Class',
    year: 2023,
    price: 48990,
    mileage: 12000,
    description: 'Premium comfort and performance with advanced safety features.',
    exteriorColor: 'Obsidian Black',
    interiorColor: 'Mocha Leather',
    transmission: '9-Speed Automatic',
    fuelType: 'Gasoline',
    engine: '2.0L Turbo I4',
    bodyStyle: 'Sedan',
    doors: 4,
    passengers: 5,
    features: ['Panoramic Sunroof', 'Burmeister Audio', 'Heated Seats', 'Apple CarPlay', 'Android Auto']
  },
  {
    make: 'Audi',
    model: 'A4',
    year: 2023,
    price: 42990,
    mileage: 18000,
    description: 'Sophisticated styling and advanced tech in a compact luxury package.',
    exteriorColor: 'Navarra Blue',
    interiorColor: 'Black Leather',
    transmission: '7-Speed Automatic',
    fuelType: 'Gasoline',
    engine: '2.0L Turbo I4',
    bodyStyle: 'Sedan',
    doors: 4,
    passengers: 5,
    features: ['Virtual Cockpit', 'Bang & Olufsen Audio', 'Quattro AWD', 'Adaptive Cruise Control']
  },
  {
    make: 'Lexus',
    model: 'ES',
    year: 2023,
    price: 42990,
    mileage: 10000,
    description: 'Reliable luxury with exceptional comfort and resale value.',
    exteriorColor: 'Ultra White',
    interiorColor: 'NuLuxe',
    transmission: '8-Speed Automatic',
    fuelType: 'Gasoline',
    engine: '3.5L V6',
    bodyStyle: 'Sedan',
    doors: 4,
    passengers: 5,
    features: ['Mark Levinson Audio', 'Heated Seats', 'Moonroof', 'Lexus Safety System+']
  },
  {
    make: 'Cadillac',
    model: 'CT5',
    year: 2023,
    price: 39990,
    mileage: 20000,
    description: 'American luxury with sporty performance and modern tech.',
    exteriorColor: 'Raven Black',
    interiorColor: 'Jet Black Leather',
    transmission: '10-Speed Automatic',
    fuelType: 'Gasoline',
    engine: '2.0L Turbo I4',
    bodyStyle: 'Sedan',
    doors: 4,
    passengers: 5,
    features: ['Super Cruise', 'Bose Audio', 'Heated Seats', 'Wireless Charging']
  },
  {
    make: 'Genesis',
    model: 'G80',
    year: 2023,
    price: 52990,
    mileage: 8000,
    description: 'Korean luxury with premium features and striking design.',
    exteriorColor: 'Uyuni White',
    interiorColor: 'Brown Leather',
    transmission: '8-Speed Automatic',
    fuelType: 'Gasoline',
    engine: '3.5L Turbo V6',
    bodyStyle: 'Sedan',
    doors: 4,
    passengers: 5,
    features: ['Lexicon Audio', 'Heated & Ventilated Seats', 'Head-Up Display', '360 Camera']
  },
  {
    make: 'Volvo',
    model: 'S60',
    year: 2023,
    price: 46990,
    mileage: 14000,
    description: 'Swedish luxury with focus on safety and minimalist design.',
    exteriorColor: 'Crystal White',
    interiorColor: 'Charcoal Leather',
    transmission: '8-Speed Automatic',
    fuelType: 'Gasoline',
    engine: '2.0L Turbo I4',
    bodyStyle: 'Sedan',
    doors: 4,
    passengers: 5,
    features: ['Bowers & Wilkins Audio', 'Pilot Assist', 'Heated Seats', 'Panoramic Sunroof']
  },
  {
    make: 'Infiniti',
    model: 'Q50',
    year: 2023,
    price: 42990,
    mileage: 16000,
    description: 'Sport-oriented luxury sedan with dynamic handling.',
    exteriorColor: 'Dynamic Sunstone',
    interiorColor: 'Graphite Leather',
    transmission: '7-Speed Automatic',
    fuelType: 'Gasoline',
    engine: '3.0L Twin-Turbo V6',
    bodyStyle: 'Sedan',
    doors: 4,
    passengers: 5,
    features: ['Bose Audio', 'Heated Seats', 'Around View Monitor', 'Direct Adaptive Steering']
  },
  {
    make: 'Acura',
    model: 'TLX',
    year: 2023,
    price: 44990,
    mileage: 11000,
    description: 'Precision crafted performance with Japanese reliability.',
    exteriorColor: 'Performance Red',
    interiorColor: 'Ebony Leather',
    transmission: '10-Speed Automatic',
    fuelType: 'Gasoline',
    engine: '2.0L Turbo I4',
    bodyStyle: 'Sedan',
    doors: 4,
    passengers: 5,
    features: ['ELS Audio', 'Heated Seats', 'AcuraWatch', 'Wireless Apple CarPlay']
  },
  {
    make: 'Lincoln',
    model: 'MKZ',
    year: 2023,
    price: 41990,
    mileage: 13000,
    description: 'American luxury with comfort-focused design.',
    exteriorColor: 'Ink Blue',
    interiorColor: 'Venetian Leather',
    transmission: '6-Speed Automatic',
    fuelType: 'Gasoline',
    engine: '2.0L Turbo I4',
    bodyStyle: 'Sedan',
    doors: 4,
    passengers: 5,
    features: ['Revel Audio', 'Heated Seats', 'Panoramic Roof', 'Lincoln Co-Pilot360']
  },
  {
    make: 'Tesla',
    model: 'Model 3',
    year: 2023,
    price: 42990,
    mileage: 5000,
    description: 'Electric innovation with cutting-edge technology and performance.',
    exteriorColor: 'Pearl White',
    interiorColor: 'Black Premium',
    transmission: 'Single-Speed Automatic',
    fuelType: 'Electric',
    engine: 'Electric Motor',
    bodyStyle: 'Sedan',
    doors: 4,
    passengers: 5,
    features: ['Autopilot', 'Premium Audio', 'Heated Seats', 'Glass Roof', 'Over-the-Air Updates']
  },
  {
    make: 'Porsche',
    model: 'Taycan',
    year: 2023,
    price: 82990,
    mileage: 3000,
    description: 'German engineering meets electric performance.',
    exteriorColor: 'Frozen Blue',
    interiorColor: 'Black Leather',
    transmission: '2-Speed Automatic',
    fuelType: 'Electric',
    engine: 'Electric Motor',
    bodyStyle: 'Sedan',
    doors: 4,
    passengers: 4,
    features: ['Porsche InnoDrive', 'Burmester Audio', 'Adaptive Air Suspension', 'Matrix LED Headlights']
  },
  {
    make: 'Jaguar',
    model: 'XE',
    year: 2023,
    price: 44990,
    mileage: 17000,
    description: 'British luxury with sporty character and elegant design.',
    exteriorColor: 'Indus Silver',
    interiorColor: 'Ebony Leather',
    transmission: '8-Speed Automatic',
    fuelType: 'Gasoline',
    engine: '2.0L Turbo I4',
    bodyStyle: 'Sedan',
    doors: 4,
    passengers: 5,
    features: ['Meridian Audio', 'Heated Seats', 'JaguarDrive Control', 'All Surface Progress Control']
  },
  {
    make: 'Land Rover',
    model: 'Discovery Sport',
    year: 2023,
    price: 46990,
    mileage: 12000,
    description: 'Versatile luxury SUV capable of on-road comfort and off-road adventure.',
    exteriorColor: 'Fuji White',
    interiorColor: 'Ebony Leather',
    transmission: '9-Speed Automatic',
    fuelType: 'Gasoline',
    engine: '2.0L Turbo I4',
    bodyStyle: 'SUV',
    doors: 5,
    passengers: 5,
    features: ['Meridian Audio', 'Heated Seats', 'Terrain Response', 'Panoramic Roof']
  },
  {
    make: 'BMW',
    model: 'X3',
    year: 2023,
    price: 49990,
    mileage: 9000,
    description: 'Compact luxury SUV with driving dynamics and practicality.',
    exteriorColor: 'Phytonic Blue',
    interiorColor: 'Black Vernasca Leather',
    transmission: '8-Speed Automatic',
    fuelType: 'Gasoline',
    engine: '2.0L Turbo I4',
    bodyStyle: 'SUV',
    doors: 5,
    passengers: 5,
    features: ['Harman Kardon Audio', 'Heated Seats', 'Panoramic Sunroof', 'BMW Assist eCall']
  },
  {
    make: 'Mercedes-Benz',
    model: 'GLC',
    year: 2023,
    price: 47990,
    mileage: 14000,
    description: 'Compact luxury SUV with premium comfort and advanced safety.',
    exteriorColor: 'Polar White',
    interiorColor: 'Black MB-Tex',
    transmission: '9-Speed Automatic',
    fuelType: 'Gasoline',
    engine: '2.0L Turbo I4',
    bodyStyle: 'SUV',
    doors: 5,
    passengers: 5,
    features: ['Burmeister Audio', 'Heated Seats', 'Power Liftgate', 'MBUX Infotainment']
  },
  {
    make: 'Audi',
    model: 'Q5',
    year: 2023,
    price: 48990,
    mileage: 11000,
    description: 'Balanced performance and luxury in a compact SUV package.',
    exteriorColor: 'Mythos Black',
    interiorColor: 'Black Leather',
    transmission: '7-Speed Automatic',
    fuelType: 'Gasoline',
    engine: '2.0L Turbo I4',
    bodyStyle: 'SUV',
    doors: 5,
    passengers: 5,
    features: ['Bang & Olufsen Audio', 'Heated Seats', 'Panoramic Sunroof', 'Quattro AWD']
  },
  {
    make: 'Lexus',
    model: 'NX',
    year: 2023,
    price: 41990,
    mileage: 15000,
    description: 'Compact luxury SUV with hybrid efficiency and reliability.',
    exteriorColor: 'Nebula Gray',
    interiorColor: 'NuLuxe',
    transmission: 'CVT Automatic',
    fuelType: 'Hybrid',
    engine: '2.5L I4 Hybrid',
    bodyStyle: 'SUV',
    doors: 5,
    passengers: 5,
    features: ['Mark Levinson Audio', 'Heated Seats', 'Power Liftgate', 'Lexus Safety System+']
  },
  {
    make: 'Volvo',
    model: 'XC60',
    year: 2023,
    price: 51990,
    mileage: 7000,
    description: 'Swedish luxury SUV with focus on safety and family comfort.',
    exteriorColor: 'Onyx Black',
    interiorColor: 'Charcoal Leather',
    transmission: '8-Speed Automatic',
    fuelType: 'Gasoline',
    engine: '2.0L Turbo I4',
    bodyStyle: 'SUV',
    doors: 5,
    passengers: 5,
    features: ['Bowers & Wilkins Audio', 'Heated & Ventilated Seats', 'Panoramic Sunroof', 'Pilot Assist']
  },
  {
    make: 'Genesis',
    model: 'GV70',
    year: 2023,
    price: 49990,
    mileage: 8000,
    description: 'Compact luxury SUV with premium features and dynamic styling.',
    exteriorColor: 'Savile Silver',
    interiorColor: 'Brown Leather',
    transmission: '8-Speed Automatic',
    fuelType: 'Gasoline',
    engine: '2.5L Turbo I4',
    bodyStyle: 'SUV',
    doors: 5,
    passengers: 5,
    features: ['Lexicon Audio', 'Heated & Ventilated Seats', 'Head-Up Display', '360 Camera']
  }
];

async function main() {
  console.log('Seeding database with cars...');

  for (const car of carData) {
    const carId = Math.random().toString(36).substr(2, 9);
    const stockNumber = 'STK' + Math.floor(Math.random() * 90000 + 10000);
    const vin = '1HGCM' + Math.random().toString(36).substr(2, 9).toUpperCase();

    await prisma.car.create({
      data: {
        id: carId,
        make: car.make,
        model: car.model,
        year: car.year,
        price: car.price,
        mileage: car.mileage,
        vin: vin,
        stockNumber: stockNumber,
        description: car.description,
        exteriorColor: car.exteriorColor,
        interiorColor: car.interiorColor,
        transmission: car.transmission,
        fuelType: car.fuelType,
        engine: car.engine,
        bodyStyle: car.bodyStyle,
        doors: car.doors,
        passengers: car.passengers,
        features: JSON.stringify(car.features),
        isFeatured: Math.random() > 0.7, // 30% chance to be featured
        isNewArrival: Math.random() > 0.8, // 20% chance to be new arrival
        isSpecialOffer: Math.random() > 0.85, // 15% chance to be special offer
        isSold: false,
        status: 'available'
      }
    });
  }

  console.log('Database seeded successfully!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });